.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
dlabel jtbl_8001223C
/* 2A3C 8001223C 942E0A80 */ .word .L800A2E94
/* 2A40 80012240 942E0A80 */ .word .L800A2E94
/* 2A44 80012244 942E0A80 */ .word .L800A2E94
/* 2A48 80012248 982F0A80 */ .word .L800A2F98
/* 2A4C 8001224C 942E0A80 */ .word .L800A2E94
/* 2A50 80012250 DC2E0A80 */ .word .L800A2EDC
/* 2A54 80012254 EC2E0A80 */ .word .L800A2EEC
/* 2A58 80012258 442F0A80 */ .word .L800A2F44
/* 2A5C 8001225C 942E0A80 */ .word .L800A2E94
/* 2A60 80012260 DC2E0A80 */ .word .L800A2EDC
/* 2A64 80012264 642F0A80 */ .word .L800A2F64
/* 2A68 80012268 702F0A80 */ .word .L800A2F70
/* 2A6C 8001226C 982F0A80 */ .word .L800A2F98
/* 2A70 80012270 982F0A80 */ .word .L800A2F98
/* 2A74 80012274 982F0A80 */ .word .L800A2F98
/* 2A78 80012278 DC2E0A80 */ .word .L800A2EDC
/* 2A7C 8001227C 982F0A80 */ .word .L800A2F98
/* 2A80 80012280 EC2E0A80 */ .word .L800A2EEC
/* 2A84 80012284 942E0A80 */ .word .L800A2E94
/* 2A88 80012288 00000000 */ .word 0x00000000
.size jtbl_8001223C, . - jtbl_8001223C

dlabel jtbl_8001228C
/* 2A8C 8001228C C42F0A80 */ .word .L800A2FC4
/* 2A90 80012290 CC2F0A80 */ .word .L800A2FCC
/* 2A94 80012294 CC2F0A80 */ .word .L800A2FCC
/* 2A98 80012298 8C300A80 */ .word .L800A308C
/* 2A9C 8001229C CC2F0A80 */ .word .L800A2FCC
/* 2AA0 800122A0 CC2F0A80 */ .word .L800A2FCC
/* 2AA4 800122A4 40300A80 */ .word .L800A3040
/* 2AA8 800122A8 50300A80 */ .word .L800A3050
/* 2AAC 800122AC CC2F0A80 */ .word .L800A2FCC
/* 2AB0 800122B0 CC2F0A80 */ .word .L800A2FCC
/* 2AB4 800122B4 CC2F0A80 */ .word .L800A2FCC
/* 2AB8 800122B8 D82F0A80 */ .word .L800A2FD8
/* 2ABC 800122BC 8C300A80 */ .word .L800A308C
/* 2AC0 800122C0 8C300A80 */ .word .L800A308C
/* 2AC4 800122C4 70300A80 */ .word .L800A3070
/* 2AC8 800122C8 CC2F0A80 */ .word .L800A2FCC
/* 2ACC 800122CC 8C300A80 */ .word .L800A308C
/* 2AD0 800122D0 40300A80 */ .word .L800A3040
/* 2AD4 800122D4 CC2F0A80 */ .word .L800A2FCC
/* 2AD8 800122D8 00000000 */ .word 0x00000000
.size jtbl_8001228C, . - jtbl_8001228C


.section .text
/* Generated by spimdisasm 1.21.0 */

glabel SteerSwitchMode
/* 9364C 800A2E4C B8F9838F */  lw         $v1, %gp_rel(Raziel + 0x388)($gp)
/* 93650 800A2E50 E0FFBD27 */  addiu      $sp, $sp, -0x20
/* 93654 800A2E54 1400B1AF */  sw         $s1, 0x14($sp)
/* 93658 800A2E58 21888000 */  addu       $s1, $a0, $zero
/* 9365C 800A2E5C 1800B2AF */  sw         $s2, 0x18($sp)
/* 93660 800A2E60 2190A000 */  addu       $s2, $a1, $zero
/* 93664 800A2E64 1C00BFAF */  sw         $ra, 0x1C($sp)
/* 93668 800A2E68 1300622C */  sltiu      $v0, $v1, 0x13
/* 9366C 800A2E6C 4A004010 */  beqz       $v0, .L800A2F98
/* 93670 800A2E70 1000B0AF */   sw        $s0, 0x10($sp)
/* 93674 800A2E74 0180023C */  lui        $v0, %hi(jtbl_8001223C)
/* 93678 800A2E78 3C224224 */  addiu      $v0, $v0, %lo(jtbl_8001223C)
/* 9367C 800A2E7C 80180300 */  sll        $v1, $v1, 2
/* 93680 800A2E80 21186200 */  addu       $v1, $v1, $v0
/* 93684 800A2E84 0000628C */  lw         $v0, 0x0($v1)
/* 93688 800A2E88 00000000 */  nop
/* 9368C 800A2E8C 08004000 */  jr         $v0
/* 93690 800A2E90 00000000 */   nop
.L800A2E94:
/* 93694 800A2E94 C8013026 */  addiu      $s0, $s1, 0x1C8
/* 93698 800A2E98 21200002 */  addu       $a0, $s0, $zero
/* 9369C 800A2E9C 01000524 */  addiu      $a1, $zero, 0x1
/* 936A0 800A2EA0 E541020C */  jal        G2Anim_IsControllerActive
/* 936A4 800A2EA4 0E000624 */   addiu     $a2, $zero, 0xE
/* 936A8 800A2EA8 3B004010 */  beqz       $v0, .L800A2F98
/* 936AC 800A2EAC 21200002 */   addu      $a0, $s0, $zero
/* 936B0 800A2EB0 01000524 */  addiu      $a1, $zero, 0x1
/* 936B4 800A2EB4 8D41020C */  jal        G2Anim_DisableController
/* 936B8 800A2EB8 0E000624 */   addiu     $a2, $zero, 0xE
/* 936BC 800A2EBC C0F98297 */  lhu        $v0, %gp_rel(Raziel + 0x390)($gp)
/* 936C0 800A2EC0 00000000 */  nop
/* 936C4 800A2EC4 780022A6 */  sh         $v0, 0x78($s1)
/* 936C8 800A2EC8 C0F98297 */  lhu        $v0, %gp_rel(Raziel + 0x390)($gp)
/* 936CC 800A2ECC 00000000 */  nop
/* 936D0 800A2ED0 B6F982A7 */  sh         $v0, %gp_rel(Raziel + 0x386)($gp)
/* 936D4 800A2ED4 E68B0208 */  j          .L800A2F98
/* 936D8 800A2ED8 00000000 */   nop
.L800A2EDC:
/* 936DC 800A2EDC 6E8B020C */  jal        SteerDisableAutoFace
/* 936E0 800A2EE0 21202002 */   addu      $a0, $s1, $zero
/* 936E4 800A2EE4 E68B0208 */  j          .L800A2F98
/* 936E8 800A2EE8 00000000 */   nop
.L800A2EEC:
/* 936EC 800A2EEC 06000224 */  addiu      $v0, $zero, 0x6
/* 936F0 800A2EF0 29004212 */  beq        $s2, $v0, .L800A2F98
/* 936F4 800A2EF4 0B000224 */   addiu     $v0, $zero, 0xB
/* 936F8 800A2EF8 27004212 */  beq        $s2, $v0, .L800A2F98
/* 936FC 800A2EFC 10000224 */   addiu     $v0, $zero, 0x10
/* 93700 800A2F00 25004212 */  beq        $s2, $v0, .L800A2F98
/* 93704 800A2F04 11000224 */   addiu     $v0, $zero, 0x11
/* 93708 800A2F08 23004212 */  beq        $s2, $v0, .L800A2F98
/* 9370C 800A2F0C C8013026 */   addiu     $s0, $s1, 0x1C8
/* 93710 800A2F10 21200002 */  addu       $a0, $s0, $zero
/* 93714 800A2F14 01000524 */  addiu      $a1, $zero, 0x1
/* 93718 800A2F18 E541020C */  jal        G2Anim_IsControllerActive
/* 9371C 800A2F1C 0E000624 */   addiu     $a2, $zero, 0xE
/* 93720 800A2F20 05004010 */  beqz       $v0, .L800A2F38
/* 93724 800A2F24 21200002 */   addu      $a0, $s0, $zero
/* 93728 800A2F28 01000524 */  addiu      $a1, $zero, 0x1
/* 9372C 800A2F2C 0E000624 */  addiu      $a2, $zero, 0xE
/* 93730 800A2F30 9D41020C */  jal        G2Anim_InterpDisableController
/* 93734 800A2F34 58020724 */   addiu     $a3, $zero, 0x258
.L800A2F38:
/* 93738 800A2F38 40FB80A7 */  sh         $zero, %gp_rel(Raziel + 0x510)($gp)
/* 9373C 800A2F3C E68B0208 */  j          .L800A2F98
/* 93740 800A2F40 00000000 */   nop
.L800A2F44:
/* 93744 800A2F44 B8F9828F */  lw         $v0, %gp_rel(Raziel + 0x388)($gp)
/* 93748 800A2F48 00000000 */  nop
/* 9374C 800A2F4C 12004212 */  beq        $s2, $v0, .L800A2F98
/* 93750 800A2F50 00000000 */   nop
/* 93754 800A2F54 798C020C */  jal        razDeinitWallCrawlSteering
/* 93758 800A2F58 21202002 */   addu      $a0, $s1, $zero
/* 9375C 800A2F5C E68B0208 */  j          .L800A2F98
/* 93760 800A2F60 00000000 */   nop
.L800A2F64:
/* 93764 800A2F64 90FA80AF */  sw         $zero, %gp_rel(Raziel + 0x460)($gp)
/* 93768 800A2F68 E68B0208 */  j          .L800A2F98
/* 9376C 800A2F6C 00000000 */   nop
.L800A2F70:
/* 93770 800A2F70 90AC8427 */  addiu      $a0, $gp, %gp_rel(theCamera)
/* 93774 800A2F74 1F6F000C */  jal        CAMERA_EndSwimThrowMode
/* 93778 800A2F78 00000000 */   nop
/* 9377C 800A2F7C 90AC8427 */  addiu      $a0, $gp, %gp_rel(theCamera)
/* 93780 800A2F80 21280000 */  addu       $a1, $zero, $zero
/* 93784 800A2F84 E86E000C */  jal        CAMERA_SetLookRot
/* 93788 800A2F88 2130A000 */   addu      $a2, $a1, $zero
/* 9378C 800A2F8C ACFA8297 */  lhu        $v0, %gp_rel(Raziel + 0x47C)($gp)
/* 93790 800A2F90 00000000 */  nop
/* 93794 800A2F94 40FB82A7 */  sh         $v0, %gp_rel(Raziel + 0x510)($gp)
.L800A2F98:
/* 93798 800A2F98 98F980AF */  sw         $zero, %gp_rel(Raziel + 0x368)($gp)
/* 9379C 800A2F9C 1300422E */  sltiu      $v0, $s2, 0x13
/* 937A0 800A2FA0 3A004010 */  beqz       $v0, .L800A308C
/* 937A4 800A2FA4 0180023C */   lui       $v0, %hi(jtbl_8001228C)
/* 937A8 800A2FA8 8C224224 */  addiu      $v0, $v0, %lo(jtbl_8001228C)
/* 937AC 800A2FAC 80181200 */  sll        $v1, $s2, 2
/* 937B0 800A2FB0 21186200 */  addu       $v1, $v1, $v0
/* 937B4 800A2FB4 0000628C */  lw         $v0, 0x0($v1)
/* 937B8 800A2FB8 00000000 */  nop
/* 937BC 800A2FBC 08004000 */  jr         $v0
/* 937C0 800A2FC0 00000000 */   nop
.L800A2FC4:
/* 937C4 800A2FC4 44FB80A7 */  sh         $zero, %gp_rel(Raziel + 0x514)($gp)
/* 937C8 800A2FC8 40FB80A7 */  sh         $zero, %gp_rel(Raziel + 0x510)($gp)
.L800A2FCC:
/* 937CC 800A2FCC 98F980AF */  sw         $zero, %gp_rel(Raziel + 0x368)($gp)
/* 937D0 800A2FD0 238C0208 */  j          .L800A308C
/* 937D4 800A2FD4 00000000 */   nop
.L800A2FD8:
/* 937D8 800A2FD8 40AD8387 */  lh         $v1, %gp_rel(theCamera + 0xB0)($gp)
/* 937DC 800A2FDC 00100224 */  addiu      $v0, $zero, 0x1000
/* 937E0 800A2FE0 23184300 */  subu       $v1, $v0, $v1
/* 937E4 800A2FE4 40FB8287 */  lh         $v0, %gp_rel(Raziel + 0x510)($gp)
/* 937E8 800A2FE8 FF0F6330 */  andi       $v1, $v1, 0xFFF
/* 937EC 800A2FEC ACFA82AF */  sw         $v0, %gp_rel(Raziel + 0x47C)($gp)
/* 937F0 800A2FF0 FFFB6224 */  addiu      $v0, $v1, -0x401
/* 937F4 800A2FF4 FF03422C */  sltiu      $v0, $v0, 0x3FF
/* 937F8 800A2FF8 03004010 */  beqz       $v0, .L800A3008
/* 937FC 800A2FFC FFF76224 */   addiu     $v0, $v1, -0x801
/* 93800 800A3000 068C0208 */  j          .L800A3018
/* 93804 800A3004 00040324 */   addiu     $v1, $zero, 0x400
.L800A3008:
/* 93808 800A3008 FF03422C */  sltiu      $v0, $v0, 0x3FF
/* 9380C 800A300C 02004010 */  beqz       $v0, .L800A3018
/* 93810 800A3010 00000000 */   nop
/* 93814 800A3014 000C0324 */  addiu      $v1, $zero, 0xC00
.L800A3018:
/* 93818 800A3018 90AC8427 */  addiu      $a0, $gp, %gp_rel(theCamera)
/* 9381C 800A301C 40FB83A7 */  sh         $v1, %gp_rel(Raziel + 0x510)($gp)
/* 93820 800A3020 0F6F000C */  jal        CAMERA_StartSwimThrowMode
/* 93824 800A3024 00000000 */   nop
/* 93828 800A3028 90AC8427 */  addiu      $a0, $gp, %gp_rel(theCamera)
/* 9382C 800A302C 21300000 */  addu       $a2, $zero, $zero
/* 93830 800A3030 40FB8287 */  lh         $v0, %gp_rel(Raziel + 0x510)($gp)
/* 93834 800A3034 00100524 */  addiu      $a1, $zero, 0x1000
/* 93838 800A3038 E86E000C */  jal        CAMERA_SetLookRot
/* 9383C 800A303C 2328A200 */   subu      $a1, $a1, $v0
.L800A3040:
/* 93840 800A3040 01000224 */  addiu      $v0, $zero, 0x1
/* 93844 800A3044 98F982AF */  sw         $v0, %gp_rel(Raziel + 0x368)($gp)
/* 93848 800A3048 238C0208 */  j          .L800A308C
/* 9384C 800A304C 00000000 */   nop
.L800A3050:
/* 93850 800A3050 B8F9828F */  lw         $v0, %gp_rel(Raziel + 0x388)($gp)
/* 93854 800A3054 00000000 */  nop
/* 93858 800A3058 0C004212 */  beq        $s2, $v0, .L800A308C
/* 9385C 800A305C 00000000 */   nop
/* 93860 800A3060 2A8C020C */  jal        razInitWallCrawlSteering
/* 93864 800A3064 21202002 */   addu      $a0, $s1, $zero
/* 93868 800A3068 238C0208 */  j          .L800A308C
/* 9386C 800A306C 00000000 */   nop
.L800A3070:
/* 93870 800A3070 08FA828F */  lw         $v0, %gp_rel(Raziel + 0x3D8)($gp)
/* 93874 800A3074 00000000 */  nop
/* 93878 800A3078 3000458C */  lw         $a1, 0x30($v0)
/* 9387C 800A307C 5C002426 */  addiu      $a0, $s1, 0x5C
/* 93880 800A3080 87E8000C */  jal        MATH3D_AngleFromPosToPos
/* 93884 800A3084 5C00A524 */   addiu     $a1, $a1, 0x5C
/* 93888 800A3088 780022A6 */  sh         $v0, 0x78($s1)
.L800A308C:
/* 9388C 800A308C 1C00BF8F */  lw         $ra, 0x1C($sp)
/* 93890 800A3090 B8F992AF */  sw         $s2, %gp_rel(Raziel + 0x388)($gp)
/* 93894 800A3094 1800B28F */  lw         $s2, 0x18($sp)
/* 93898 800A3098 1400B18F */  lw         $s1, 0x14($sp)
/* 9389C 800A309C 1000B08F */  lw         $s0, 0x10($sp)
/* 938A0 800A30A0 0800E003 */  jr         $ra
/* 938A4 800A30A4 2000BD27 */   addiu     $sp, $sp, 0x20
.size SteerSwitchMode, . - SteerSwitchMode
