.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.18.0 */

dlabel soundBuffer
/* C28AC 800D75BC */ .space 0x33C8

dlabel LoadQueue
/* C5C74 800DA984 */ .space 0x1180

dlabel StCdIntrFlag
/* C6DF4 800DBB04 */ .space 0x04

dlabel gMcmenu
/* C6DF8 800DBB08 */ .space 0x200

dlabel gMemcard
/* C6FF8 800DBD08 */ .space 0x160

dlabel _que
/* C7158 800DBE68 */ .space 0x1800

dlabel GsOUT_PACKET_P_dup1
/* C8958 800DD668 */ .space 0x2680

dlabel SpuCommonError
/* CAFD8 800DFCE8 */ .space 0x14

dlabel StFunc1
/* CAFEC 800DFCFC */ .space 0x04

dlabel StFunc2
/* CAFF0 800DFD00 */ .space 0x04

dlabel StEmu_Addr
/* CAFF4 800DFD04 */ .space 0x04

dlabel CChannel
/* CAFF8 800DFD08 */ .space 0x04

dlabel StCHANNEL
/* CAFFC 800DFD0C */ .space 0x04

dlabel Stframe_no
/* CB000 800DFD10 */ .space 0x04

dlabel StRgb24
/* CB004 800DFD14 */ .space 0x04

dlabel StEndFrame
/* CB008 800DFD18 */ .space 0x04

dlabel StSTART_FLAG
/* CB00C 800DFD1C */ .space 0x04

dlabel StEmu_Idx
/* CB010 800DFD20 */ .space 0x04

dlabel Stsector_offset
/* CB014 800DFD24 */ .space 0x04

dlabel StFinalSector
/* CB018 800DFD28 */ .space 0x04

dlabel StRingBase
/* CB01C 800DFD2C */ .space 0x04

dlabel StRingAddr
/* CB020 800DFD30 */ .space 0x04

dlabel StRingIdx1
/* CB024 800DFD34 */ .space 0x04

dlabel StRingIdx2
/* CB028 800DFD38 */ .space 0x04

dlabel StRingIdx3
/* CB02C 800DFD3C */ .space 0x04

dlabel StRingSize
/* CB030 800DFD40 */ .space 0x04

dlabel StStartFrame
/* CB034 800DFD44 */ .space 0x74

dlabel StMode
/* CB0A8 800DFDB8 */ .space 0x04

dlabel _spu_RQ
/* CB0AC 800DFDBC */ .space 0x74

dlabel GlobalCallback
/* CB120 800DFE30 */ .space 0x0C

dlabel _waitTime
/* CB12C 800DFE3C */ .space 0x04

dlabel D_800DFE40
/* CB130 800DFE40 */ .space 0x34

dlabel D_800DFE74
/* CB164 800DFE74 */ .space 0x754
