.include "macro.inc"

.section .rodata

/* Generated by spimdisasm 1.21.0 */

.align 2
dlabel D_80012424
/* 2C24 80012424 */ .asciz "CINEMA : Version number is wrong. Not playing the cinematics.\n"
.align 2
.size D_80012424, . - D_80012424

.align 2
dlabel D_80012464
/* 2C64 80012464 */ .asciz "cinemax"
.align 2
.size D_80012464, . - D_80012464

.align 2
dlabel D_8001246C
/* 2C6C 8001246C */ .asciz "cinema timeout\n"
.align 2
.size D_8001246C, . - D_8001246C

.align 2
dlabel D_8001247C
/* 2C7C 8001247C */ .asciz "\\CHRONO%d.STR;1"
.align 2
.size D_8001247C, . - D_8001247C

.align 2
dlabel D_8001248C
/* 2C8C 8001248C */ .asciz "\\kain2\\object\\mcardx\\mcardx.drm"
.align 2
.size D_8001248C, . - D_8001248C

.align 2
dlabel D_800124AC
/* 2CAC 800124AC */ .asciz "%s:%ld: %s\n"
.align 2
.size D_800124AC, . - D_800124AC

.align 2
dlabel D_800124B8
/* 2CB8 800124B8 */ .asciz "%s:%ld: assertion failure\n"
.align 2
.align 2
/* 2CD4 800124D4 */ .asciz "$Id: intr.c,v 1.75 1997/02/07 09:00:36 makoto Exp $"
.align 2
.size D_800124B8, . - D_800124B8

.align 2
dlabel D_80012508
/* 2D08 80012508 */ .asciz "unexpected interrupt(%04x)\n"
.align 2
.size D_80012508, . - D_80012508

.align 2
dlabel D_80012524
/* 2D24 80012524 */ .asciz "intr timeout(%04x:%04x)\n"
.align 2
.align 2
/* 2D40 80012540 */ .asciz ""
.align 2
.align 2
/* 2D44 80012544 */ .asciz "$Id: sys.c,v 1.140 1998/01/12 07:52:27 noda Exp yos $"
.align 2
.size D_80012524, . - D_80012524

.align 2
dlabel D_8001257C
/* 2D7C 8001257C */ .asciz "ResetGraph:jtb=%08x,env=%08x\n"
.align 2
.size D_8001257C, . - D_8001257C

.align 2
dlabel D_8001259C
/* 2D9C 8001259C */ .asciz "ResetGraph(%d)...\n"
.align 2
.size D_8001259C, . - D_8001259C

.align 2
dlabel D_800125B0
/* 2DB0 800125B0 */ .asciz "SetGraphDebug:level:%d,type:%d reverse:%d\n"
.align 2
.align 2
/* 2DDC 800125DC */ .asciz "SetGrapQue(%d)...\n"
.align 2
.size D_800125B0, . - D_800125B0

.align 2
dlabel D_800125F0
/* 2DF0 800125F0 */ .asciz "DrawSyncCallback(%08x)...\n"
.align 2
.size D_800125F0, . - D_800125F0

.align 2
dlabel D_8001260C
/* 2E0C 8001260C */ .asciz "SetDispMask(%d)...\n"
.align 2
.size D_8001260C, . - D_8001260C

.align 2
dlabel D_80012620
/* 2E20 80012620 */ .asciz "DrawSync(%d)...\n"
.align 2
.size D_80012620, . - D_80012620

.align 2
dlabel D_80012634
/* 2E34 80012634 */ .asciz "%s:bad RECT"
.align 2
.size D_80012634, . - D_80012634

.align 2
dlabel D_80012640
/* 2E40 80012640 */ .asciz "(%d,%d)-(%d,%d)\n"
.align 2
.size D_80012640, . - D_80012640

.align 2
dlabel D_80012654
/* 2E54 80012654 */ .asciz "%s:"
.align 2
.size D_80012654, . - D_80012654

.align 2
dlabel D_80012658
/* 2E58 80012658 */ .asciz "ClearImage"
.align 2
.align 2
/* 2E64 80012664 */ .asciz "ClearImage2"
.align 2
.size D_80012658, . - D_80012658

.align 2
dlabel D_80012670
/* 2E70 80012670 */ .asciz "LoadImage"
.align 2
.align 2
/* 2E7C 8001267C */ .asciz "StoreImage"
.align 2
.size D_80012670, . - D_80012670

.align 2
dlabel D_80012688
/* 2E88 80012688 */ .asciz "MoveImage"
.align 2
.align 2
/* 2E94 80012694 */ .asciz "ClearOTag(%08x,%d)...\n"
.align 2
.size D_80012688, . - D_80012688

.align 2
dlabel D_800126AC
/* 2EAC 800126AC */ .asciz "ClearOTagR(%08x,%d)...\n"
.align 2
.size D_800126AC, . - D_800126AC

.align 2
dlabel D_800126C4
/* 2EC4 800126C4 */ .asciz "DrawOTag(%08x)...\n"
.align 2
.size D_800126C4, . - D_800126C4

.align 2
dlabel D_800126D8
/* 2ED8 800126D8 */ .asciz "PutDrawEnv(%08x)...\n"
.align 2
.align 2
/* 2EF0 800126F0 */ .asciz "DrawOTagEnv(%08x,&08x)...\n"
.align 2
.size D_800126D8, . - D_800126D8

.align 2
dlabel D_8001270C
/* 2F0C 8001270C */ .asciz "PutDispEnv(%08x)...\n"
.align 2
.size D_8001270C, . - D_8001270C

.align 2
dlabel D_80012724
/* 2F24 80012724 */ .asciz "GPU timeout:que=%d,stat=%08x,chcr=%08x,madr=%08x\n"
.align 2
.align 2
/* 2F58 80012758 */ .asciz "LoadImage2"
.align 2
.size D_80012724, . - D_80012724

.align 2
dlabel D_80012764
/* 2F64 80012764 */ .asciz "VSync: timeout\n"
.align 2
.size D_80012764, . - D_80012764

dlabel jtbl_80012774
/* 2F74 80012774 2CDD0B80 */ .word .L800BDD2C
/* 2F78 80012778 38DD0B80 */ .word .L800BDD38
/* 2F7C 8001277C 44DD0B80 */ .word .L800BDD44
/* 2F80 80012780 50DD0B80 */ .word .L800BDD50
/* 2F84 80012784 5CDD0B80 */ .word .L800BDD5C
/* 2F88 80012788 00000000 */ .word 0x00000000
/* 2F8C 8001278C 00000000 */ .word 0x00000000
/* 2F90 80012790 00000000 */ .word 0x00000000
.size jtbl_80012774, . - jtbl_80012774

.align 2
dlabel D_80012794
/* 2F94 80012794 */ .asciz "none"
.align 2
.align 2
/* 2F9C 8001279C */ .asciz ""
.align 2
.align 2
/* 2FA0 800127A0 */ .asciz ""
.align 2
.size D_80012794, . - D_80012794

.align 2
dlabel D_800127A4
/* 2FA4 800127A4 */ .asciz "CdInit: Init failed\n"
.align 2
.align 2
/* 2FBC 800127BC */ .asciz ""
.align 2
.align 2
/* 2FC0 800127C0 */ .asciz ""
.align 2
.size D_800127A4, . - D_800127A4

.align 2
dlabel D_800127C4
/* 2FC4 800127C4 */ .asciz "%s: path level (%d) error\n"
.align 2
.size D_800127C4, . - D_800127C4

.align 2
dlabel D_800127E0
/* 2FE0 800127E0 */ .asciz "%s: dir was not found\n"
.align 2
.size D_800127E0, . - D_800127E0

.align 2
dlabel D_800127F8
/* 2FF8 800127F8 */ .asciz "CdSearchFile: disc error\n"
.align 2
.size D_800127F8, . - D_800127F8

.align 2
dlabel D_80012814
/* 3014 80012814 */ .asciz "CdSearchFile: searching %s...\n"
.align 2
.size D_80012814, . - D_80012814

.align 2
dlabel D_80012834
/* 3034 80012834 */ .asciz "%s:  found\n"
.align 2
.size D_80012834, . - D_80012834

.align 2
dlabel D_80012840
/* 3040 80012840 */ .asciz "%s: not found\n"
.align 2
.size D_80012840, . - D_80012840

.align 2
dlabel D_80012850
/* 3050 80012850 */ .asciz "CD_newmedia: Read error in cd_read(PVD)\n"
.align 2
.size D_80012850, . - D_80012850

.align 2
dlabel D_8001287C
/* 307C 8001287C */ .asciz "CD001"
.align 2
.size D_8001287C, . - D_8001287C

.align 2
dlabel D_80012884
/* 3084 80012884 */ .asciz "CD_newmedia: Disc format error in cd_read(PVD)\n"
.align 2
.size D_80012884, . - D_80012884

.align 2
dlabel D_800128B4
/* 30B4 800128B4 */ .asciz "CD_newmedia: Read error (PT:%08x)\n"
.align 2
.size D_800128B4, . - D_800128B4

.align 2
dlabel D_800128D8
/* 30D8 800128D8 */ .asciz "CD_newmedia: sarching dir..\n"
.align 2
.size D_800128D8, . - D_800128D8

.align 2
dlabel D_800128F8
/* 30F8 800128F8 */ .asciz "\t%08x,%04x,%04x,%s\n"
.align 2
.size D_800128F8, . - D_800128F8

.align 2
dlabel D_8001290C
/* 310C 8001290C */ .asciz "CD_newmedia: %d dir entries found\n"
.align 2
.size D_8001290C, . - D_8001290C

.align 2
dlabel D_80012930
/* 3130 80012930 */ .asciz "CD_cachefile: dir not found\n"
.align 2
.size D_80012930, . - D_80012930

.align 2
dlabel D_80012950
/* 3150 80012950 */ .asciz "CD_cachefile: searching...\n"
.align 2
.size D_80012950, . - D_80012950

dlabel D_8001296C
/* 316C 8001296C */ .short 0x002E
/* 316E 8001296E */ .short 0x0000
.size D_8001296C, . - D_8001296C

dlabel D_80012970
/* 3170 80012970 */ .short 0x2E2E
.size D_80012970, . - D_80012970

dlabel D_80012972
/* 3172 80012972 */ .byte 0x00
/* 3173 80012973 */ .byte 0x00
.size D_80012972, . - D_80012972

.align 2
dlabel D_80012974
/* 3174 80012974 */ .asciz "\t(%02x:%02x:%02x) %8d %s\n"
.align 2
.size D_80012974, . - D_80012974

.align 2
dlabel D_80012990
/* 3190 80012990 */ .asciz "CD_cachefile: %d files found\n"
.align 2
.align 2
/* 31B0 800129B0 */ .asciz ""
.align 2
.size D_80012990, . - D_80012990

.align 2
dlabel D_800129B4
/* 31B4 800129B4 */ .asciz "<NULL>"
.align 2
.align 2
/* 31BC 800129BC */ .asciz ""
.align 2
.align 2
/* 31C0 800129C0 */ .asciz ""
.align 2
.size D_800129B4, . - D_800129B4

dlabel jtbl_800129C4
/* 31C4 800129C4 04080C80 */ .word .L800C0804
/* 31C8 800129C8 CC070C80 */ .word .L800C07CC
/* 31CC 800129CC D4070C80 */ .word .L800C07D4
/* 31D0 800129D0 DC070C80 */ .word .L800C07DC
/* 31D4 800129D4 E4070C80 */ .word .L800C07E4
/* 31D8 800129D8 EC070C80 */ .word .L800C07EC
/* 31DC 800129DC F4070C80 */ .word .L800C07F4
/* 31E0 800129E0 FC070C80 */ .word .L800C07FC
.size jtbl_800129C4, . - jtbl_800129C4

dlabel jtbl_800129E4
/* 31E4 800129E4 C4080C80 */ .word .L800C08C4
/* 31E8 800129E8 8C080C80 */ .word .L800C088C
/* 31EC 800129EC 94080C80 */ .word .L800C0894
/* 31F0 800129F0 9C080C80 */ .word .L800C089C
/* 31F4 800129F4 A4080C80 */ .word .L800C08A4
/* 31F8 800129F8 AC080C80 */ .word .L800C08AC
/* 31FC 800129FC B4080C80 */ .word .L800C08B4
/* 3200 80012A00 BC080C80 */ .word .L800C08BC
.size jtbl_800129E4, . - jtbl_800129E4

.align 2
dlabel D_80012A04
/* 3204 80012A04 */ .asciz "DMA STATUS ERROR %x\n"
.align 2
.align 2
/* 321C 80012A1C */ .asciz ""
.align 2
.align 2
/* 3220 80012A20 */ .asciz ""
.align 2
.size D_80012A04, . - D_80012A04

.align 2
dlabel D_80012A24
/* 3224 80012A24 */ .asciz "DMA bus error: code=%08x\n"
.align 2
.size D_80012A24, . - D_80012A24

.align 2
dlabel D_80012A40
/* 3240 80012A40 */ .asciz "MADR[%d]=%08x\n"
.align 2
.align 2
/* 3250 80012A50 */ .asciz ""
.align 2
.align 2
/* 3254 80012A54 */ .asciz "CdlReadS"
.align 2
.align 2
/* 3260 80012A60 */ .asciz "CdlSeekP"
.align 2
.align 2
/* 326C 80012A6C */ .asciz "CdlSeekL"
.align 2
.align 2
/* 3278 80012A78 */ .asciz "CdlGetTD"
.align 2
.align 2
/* 3284 80012A84 */ .asciz "CdlGetTN"
.align 2
.align 2
/* 3290 80012A90 */ .asciz "CdlGetlocP"
.align 2
.align 2
/* 329C 80012A9C */ .asciz "CdlGetlocL"
.align 2
.align 2
/* 32A8 80012AA8 */ .asciz "?"
.align 2
.align 2
/* 32AC 80012AAC */ .asciz "CdlSetmode"
.align 2
.align 2
/* 32B8 80012AB8 */ .asciz "CdlSetfilter"
.align 2
.align 2
/* 32C8 80012AC8 */ .asciz "CdlDemute"
.align 2
.align 2
/* 32D4 80012AD4 */ .asciz "CdlMute"
.align 2
.align 2
/* 32DC 80012ADC */ .asciz "CdlReset"
.align 2
.align 2
/* 32E8 80012AE8 */ .asciz "CdlPause"
.align 2
.align 2
/* 32F4 80012AF4 */ .asciz "CdlStop"
.align 2
.align 2
/* 32FC 80012AFC */ .asciz "CdlStandby"
.align 2
.align 2
/* 3308 80012B08 */ .asciz "CdlReadN"
.align 2
.align 2
/* 3314 80012B14 */ .asciz "CdlBackward"
.align 2
.align 2
/* 3320 80012B20 */ .asciz "CdlForward"
.align 2
.align 2
/* 332C 80012B2C */ .asciz "CdlPlay"
.align 2
.align 2
/* 3334 80012B34 */ .asciz "CdlSetloc"
.align 2
.align 2
/* 3340 80012B40 */ .asciz "CdlNop"
.align 2
.align 2
/* 3348 80012B48 */ .asciz "CdlSync"
.align 2
.align 2
/* 3350 80012B50 */ .asciz "DiskError"
.align 2
.align 2
/* 335C 80012B5C */ .asciz "DataEnd"
.align 2
.align 2
/* 3364 80012B64 */ .asciz "Acknowledge"
.align 2
.align 2
/* 3370 80012B70 */ .asciz "Complete"
.align 2
.align 2
/* 337C 80012B7C */ .asciz "DataReady"
.align 2
.align 2
/* 3388 80012B88 */ .asciz "NoIntr"
.align 2
.size D_80012A40, . - D_80012A40

.align 2
dlabel D_80012B90
/* 3390 80012B90 */ .asciz "CD timeout: "
.align 2
.size D_80012B90, . - D_80012B90

.align 2
dlabel D_80012BA0
/* 33A0 80012BA0 */ .asciz "%s:(%s) Sync=%s, Ready=%s\n"
.align 2
.size D_80012BA0, . - D_80012BA0

.align 2
dlabel D_80012BBC
/* 33BC 80012BBC */ .asciz "DiskError: "
.align 2
.size D_80012BBC, . - D_80012BBC

.align 2
dlabel D_80012BC8
/* 33C8 80012BC8 */ .asciz "com=%s,code=(%02x:%02x)\n"
.align 2
.size D_80012BC8, . - D_80012BC8

.align 2
dlabel D_80012BE4
/* 33E4 80012BE4 */ .asciz "CDROM: unknown intr"
.align 2
.size D_80012BE4, . - D_80012BE4

.align 2
dlabel D_80012BF8
/* 33F8 80012BF8 */ .asciz "(%d)\n"
.align 2
.align 2
/* 3400 80012C00 */ .asciz ""
.align 2
.size D_80012BF8, . - D_80012BF8

dlabel jtbl_80012C04
/* 3404 80012C04 7C430C80 */ .word .L800C437C
/* 3408 80012C08 30430C80 */ .word .L800C4330
/* 340C 80012C0C 30420C80 */ .word .L800C4230
/* 3410 80012C10 FC430C80 */ .word .L800C43FC
/* 3414 80012C14 7C440C80 */ .word .L800C447C
.size jtbl_80012C04, . - jtbl_80012C04

.align 2
dlabel D_80012C18
/* 3418 80012C18 */ .asciz "CD_sync"
.align 2
.size D_80012C18, . - D_80012C18

.align 2
dlabel D_80012C20
/* 3420 80012C20 */ .asciz "CD_ready"
.align 2
.size D_80012C20, . - D_80012C20

.align 2
dlabel D_80012C2C
/* 342C 80012C2C */ .asciz "%s...\n"
.align 2
.size D_80012C2C, . - D_80012C2C

.align 2
dlabel D_80012C34
/* 3434 80012C34 */ .asciz "%s: no param\n"
.align 2
.size D_80012C34, . - D_80012C34

.align 2
dlabel D_80012C44
/* 3444 80012C44 */ .asciz "CD_cw"
.align 2
.align 2
/* 344C 80012C4C */ .asciz "$Id: bios.c,v 1.86 1997/03/28 07:42:42 makoto Exp yos $"
.align 2
.size D_80012C44, . - D_80012C44

.align 2
dlabel D_80012C84
/* 3484 80012C84 */ .asciz "CD_init:"
.align 2
.size D_80012C84, . - D_80012C84

.align 2
dlabel D_80012C90
/* 3490 80012C90 */ .asciz "addr=%08x\n"
.align 2
.size D_80012C90, . - D_80012C90

.align 2
dlabel D_80012C9C
/* 349C 80012C9C */ .asciz "CD_datasync"
.align 2
.align 2
/* 34A8 80012CA8 */ .asciz ""
.align 2
.align 2
/* 34AC 80012CAC */ .asciz ""
.align 2
.align 2
/* 34B0 80012CB0 */ .asciz ""
.align 2
.size D_80012C9C, . - D_80012C9C

.align 2
dlabel D_80012CB4
/* 34B4 80012CB4 */ .asciz "CdRead: sector error\n"
.align 2
.size D_80012CB4, . - D_80012CB4

.align 2
dlabel D_80012CCC
/* 34CC 80012CCC */ .asciz "CdRead: Shell open...\n"
.align 2
.size D_80012CCC, . - D_80012CCC

.align 2
dlabel D_80012CE4
/* 34E4 80012CE4 */ .asciz "CdRead: retry...\n"
.align 2
.align 2
/* 34F8 80012CF8 */ .asciz ""
.align 2
.align 2
/* 34FC 80012CFC */ .asciz ""
.align 2
.align 2
/* 3500 80012D00 */ .asciz ""
.align 2
.size D_80012CE4, . - D_80012CE4

.align 2
dlabel D_80012D04
/* 3504 80012D04 */ .asciz "SPU:T/O [%s]\n"
.align 2
.size D_80012D04, . - D_80012D04

.align 2
dlabel D_80012D14
/* 3514 80012D14 */ .asciz "wait (reset)"
.align 2
.size D_80012D14, . - D_80012D14

.align 2
dlabel D_80012D24
/* 3524 80012D24 */ .asciz "wait (wrdy H -> L)"
.align 2
.size D_80012D24, . - D_80012D24

.align 2
dlabel D_80012D38
/* 3538 80012D38 */ .asciz "wait (dmaf clear/W)"
.align 2
.align 2
/* 354C 80012D4C */ .asciz ""
.align 2
.align 2
/* 3550 80012D50 */ .asciz ""
.align 2
.size D_80012D38, . - D_80012D38
