.include "macro.inc"

.section .bss

/* Generated by spimdisasm 1.21.0 */

dlabel debugSoundMenu
/* C28AC 800D20AC */ .space 0x18

dlabel debugOrgFogNear
/* C28C4 800D20C4 */ .space 0x04

dlabel debugOrgFogRed
/* C28C8 800D20C8 */ .space 0x04

dlabel debugOrgFogGrn
/* C28CC 800D20CC */ .space 0x04

dlabel debugOrgFogBlu
/* C28D0 800D20D0 */ .space 0x04

dlabel debugOrgFogFar
/* C28D4 800D20D4 */ .space 0x04

dlabel statsMenu
/* C28D8 800D20D8 */ .space 0x18

dlabel debugRazielFlags1
/* C28F0 800D20F0 */ .space 0x04

dlabel debugRazielFlags2
/* C28F4 800D20F4 */ .space 0x04

dlabel debugRazielFlags3
/* C28F8 800D20F8 */ .space 0x04

dlabel point.42
/* C28FC 800D20FC */ .space 0x08

dlabel maxVelAccl.63
/* C2904 800D2104 */ .space 0x04

dlabel maxVelVel.64
/* C2908 800D2108 */ .space 0x04

dlabel wcTransformX
/* C290C 800D210C */ .space 0x20

dlabel wcTransform2X
/* C292C 800D212C */ .space 0x20

dlabel cwTransform2X
/* C294C 800D214C */ .space 0x20

dlabel combat_cam_distance
/* C296C 800D216C */ .space 0x02

dlabel combat_cam_angle
/* C296E 800D216E */ .space 0x02

dlabel combat_cam_weight
/* C2970 800D2170 */ .space 0x02

dlabel combat_cam_debounce
/* C2972 800D2172 */ .space 0x02

dlabel CenterFlag
/* C2974 800D2174 */ .space 0x08

dlabel camera_shakeOffset
/* C297C 800D217C */ .space 0x80

dlabel camera_plane
/* C29FC 800D21FC */ .space 0x08

dlabel left_point
/* C2A04 800D2204 */ .space 0x08

dlabel right_point
/* C2A0C 800D220C */ .space 0x08

dlabel hitline_rot
/* C2A14 800D2214 */ .space 0x04

dlabel ACE_amount
/* C2A18 800D2218 */ .space 0x04

dlabel splinecam_helprot
/* C2A1C 800D221C */ .space 0x08

dlabel Camera_lookHeight
/* C2A24 800D2224 */ .space 0x02

dlabel Camera_lookDist
/* C2A26 800D2226 */ .space 0x02

dlabel theCamera
/* C2A28 800D2228 */ .space 0x4C4

dlabel campoint_hw
/* C2EEC 800D26EC */ .space 0x04

dlabel campoint_hh
/* C2EF0 800D26F0 */ .space 0x04

dlabel CameraCenterDelay
/* C2EF4 800D26F4 */ .space 0x04

dlabel collide_point0
/* C2EF8 800D26F8 */ .space 0x04

dlabel collide_point1
/* C2EFC 800D26FC */ .space 0x04

dlabel collide_t0
/* C2F00 800D2700 */ .space 0x04

dlabel collide_t1
/* C2F04 800D2704 */ .space 0x04

dlabel collide_localPoint
/* C2F08 800D2708 */ .space 0x08

dlabel collide_lwTransform
/* C2F10 800D2710 */ .space 0x04

dlabel collide_normal0
/* C2F14 800D2714 */ .space 0x04

dlabel collide_normal1
/* C2F18 800D2718 */ .space 0x04

dlabel draw_stack
/* C2F1C 800D271C */ .space 0x04

dlabel modelDQP
/* C2F20 800D2720 */ .space 0x04

dlabel shadow_vertices
/* C2F24 800D2724 */ .space 0x58

dlabel fp_str
/* C2F7C 800D277C */ .space 0x200

dlabel FONT_vramBlock
/* C317C 800D297C */ .space 0x04

dlabel SpecialFogClut
/* C3180 800D2980 */ .space 0x04

dlabel fontTracker
/* C3184 800D2984 */ .space 0x620

dlabel gOt
/* C37A4 800D2FA4 */ .space 0x08

dlabel primPool
/* C37AC 800D2FAC */ .space 0x08

dlabel gPolytopeList
/* C37B4 800D2FB4 */ .space 0x04

dlabel instanceList
/* C37B8 800D2FB8 */ .space 0x04

dlabel instancePool
/* C37BC 800D2FBC */ .space 0x04

dlabel gVertexPool
/* C37C0 800D2FC0 */ .space 0x04

dlabel gLightInfo
/* C37C4 800D2FC4 */ .space 0x04

dlabel enemyPlanPool
/* C37C8 800D2FC8 */ .space 0x04

dlabel planningPool
/* C37CC 800D2FCC */ .space 0x04

dlabel GlobalObjects
/* C37D0 800D2FD0 */ .space 0x04

dlabel pause_redraw_flag
/* C37D4 800D2FD4 */ .space 0x04

dlabel pause_redraw_prim
/* C37D8 800D2FD8 */ .space 0x04

dlabel gFXT
/* C37DC 800D2FDC */ .space 0x04

dlabel InStreamUnit
/* C37E0 800D2FE0 */ .space 0x04

dlabel RENDER_currentStreamUnitID
/* C37E4 800D2FE4 */ .space 0x04

dlabel hackOT
/* C37E8 800D2FE8 */ .space 0x04

dlabel StackSave
/* C37EC 800D2FEC */ .space 0x04

dlabel fxTracker
/* C37F0 800D2FF0 */ .space 0x04

dlabel primBase
/* C37F4 800D2FF4 */ .space 0x04

dlabel lastPad.24
/* C37F8 800D2FF8 */ .space 0x04

dlabel ignoreFind
/* C37FC 800D2FFC */ .space 0x04

dlabel dualshock0_time
/* C3800 800D3000 */ .space 0x04

dlabel dualshock1_time
/* C3804 800D3004 */ .space 0x04

dlabel overrideData
/* C3808 800D3008 */ .space 0x28

/* Automatically generated and unreferenced pad */
dlabel D_800D3030
/* C3830 800D3030 */ .space 0x08

dlabel overrideCommand
/* C3838 800D3038 */ .space 0x28

dlabel controllerType
/* C3860 800D3060 */ .space 0x02

/* Automatically generated and unreferenced pad */
dlabel D_800D3062
/* C3862 800D3062 */ .space 0x02

dlabel psxData
/* C3864 800D3064 */ .space 0x04

dlabel gpbuffer1
/* C3868 800D3068 */ .space 0x22

/* Automatically generated and unreferenced pad */
dlabel D_800D308A
/* C388A 800D308A */ .space 0x02

dlabel readGPBuffer1
/* C388C 800D308C */ .space 0x22

/* Automatically generated and unreferenced pad */
dlabel D_800D30AE
/* C38AE 800D30AE */ .space 0x02

dlabel gpbuffer2
/* C38B0 800D30B0 */ .space 0x22

/* Automatically generated and unreferenced pad */
dlabel D_800D30D2
/* C38D2 800D30D2 */ .space 0x02

dlabel readGPBuffer2
/* C38D4 800D30D4 */ .space 0x22

/* Automatically generated and unreferenced pad */
dlabel D_800D30F6
/* C38F6 800D30F6 */ .space 0x02

dlabel gDummyCommand
/* C38F8 800D30F8 */ .space 0x10

dlabel gamePadControllerOut
/* C3908 800D3108 */ .space 0x04

dlabel light_sourceAndVertexFunc
/* C390C 800D310C */ .space 0x04

dlabel light_light
/* C3910 800D3110 */ .space 0x04

dlabel light_terrain
/* C3914 800D3114 */ .space 0x04

dlabel light_lightInfo
/* C3918 800D3118 */ .space 0x04

dlabel crap.35
/* C391C 800D311C */ .space 0x10

dlabel loadStatus
/* C392C 800D312C */ .space 0xA0

dlabel crap1
/* C39CC 800D31CC */ .space 0x04

dlabel mainMenuSfx
/* C39D0 800D31D0 */ .space 0x04

dlabel BexitLine
/* C39D4 800D31D4 */ .space 0x20

dlabel disp
/* C39F4 800D31F4 */ .space 0x28

dlabel devstation
/* C3A1C 800D321C */ .space 0x04

dlabel draw
/* C3A20 800D3220 */ .space 0xB8

dlabel BmenuLines
/* C3AD8 800D32D8 */ .space 0x60

dlabel __timerEvent
/* C3B38 800D3338 */ .space 0x04

dlabel clearRect
/* C3B3C 800D333C */ .space 0x20

dlabel mainMenuTimeOut
/* C3B5C 800D335C */ .space 0x04

dlabel gameTrackerX
/* C3B60 800D3360 */ .space 0x270

dlabel mainTrackerX
/* C3DD0 800D35D0 */ .space 0x10

dlabel PauseButtons
/* C3DE0 800D35E0 */ .space 0x80

dlabel sbsp_lightInfo
/* C3E60 800D3660 */ .space 0x04

dlabel crap.24
/* C3E64 800D3664 */ .space 0x0C

dlabel gSramLargestFree
/* C3E70 800D3670 */ .space 0x04

dlabel soundEffectChannelTbl
/* C3E74 800D3674 */ .space 0x240

dlabel gSramFreeBlocks
/* C40B4 800D38B4 */ .space 0x04

dlabel gSramUsedBlocks
/* C40B8 800D38B8 */ .space 0x04

dlabel gSramTotalUsed
/* C40BC 800D38BC */ .space 0x04

dlabel gSramTotalFree
/* C40C0 800D38C0 */ .space 0x04

dlabel musicInfo
/* C40C4 800D38C4 */ .space 0x4C

dlabel nextRot.50
/* C4110 800D3910 */ .space 0x08

dlabel point.53
/* C4118 800D3918 */ .space 0x08

dlabel point.56
/* C4120 800D3920 */ .space 0x08

dlabel dpoint.59
/* C4128 800D3928 */ .space 0x08

dlabel p.62
/* C4130 800D3930 */ .space 0x08

dlabel point.77
/* C4138 800D3938 */ .space 0x08

dlabel point.80
/* C4140 800D3940 */ .space 0x08

dlabel FX_ConstrictPosition
/* C4148 800D3948 */ .space 0x06

/* Automatically generated and unreferenced pad */
dlabel D_800D394E
/* C414E 800D394E */ .space 0x02

dlabel FX_ConstrictPositionPtr
/* C4150 800D3950 */ .space 0x04

dlabel FX_LastUsedPrim
/* C4154 800D3954 */ .space 0x04

dlabel FX_Frames
/* C4158 800D3958 */ .space 0x02

dlabel FX_TimeCount
/* C415A 800D395A */ .space 0x0E

dlabel Spiral_Array
/* C4168 800D3968 */ .space 0x104

/* Automatically generated and unreferenced pad */
dlabel D_800D3A6C
/* C426C 800D3A6C */ .space 0x0C

dlabel Spiral_OffsetP
/* C4278 800D3A78 */ .space 0x100

dlabel Spiral_OffsetM
/* C4378 800D3B78 */ .space 0x100

dlabel Spiral_Glow_X
/* C4478 800D3C78 */ .space 0x04

dlabel Spiral_Glow_Y
/* C447C 800D3C7C */ .space 0x04

dlabel Spiral_Glow_Size
/* C4480 800D3C80 */ .space 0x04

dlabel Spiral_Mod
/* C4484 800D3C84 */ .space 0x04

dlabel newMemTracker
/* C4488 800D3C88 */ .space 0x14

dlabel __hblankEvent
/* C449C 800D3C9C */ .space 0x04

dlabel smfDataPtr
/* C44A0 800D3CA0 */ .space 0x04

dlabel smfBytesLeft
/* C44A4 800D3CA4 */ .space 0x04

dlabel smfInfo
/* C44A8 800D3CA8 */ .space 0x04

dlabel s_zval
/* C44AC 800D3CAC */ .space 0x04

dlabel WarpGateLoadInfo
/* C44B0 800D3CB0 */ .space 0x14

dlabel MORPH_SavedLevel
/* C44C4 800D3CC4 */ .space 0x04

dlabel MORPH_Component
/* C44C8 800D3CC8 */ .space 0x06

/* Automatically generated and unreferenced pad */
dlabel D_800D3CCE
/* C44CE 800D3CCE */ .space 0x02

dlabel MORPH_Track
/* C44D0 800D3CD0 */ .space 0x04

dlabel StreamTracker
/* C44D4 800D3CD4 */ .space 0x400

dlabel MORPH_SavedFace
/* C48D4 800D40D4 */ .space 0x04

dlabel loadFree
/* C48D8 800D40D8 */ .space 0x04

dlabel loadHead
/* C48DC 800D40DC */ .space 0x04

dlabel loadTail
/* C48E0 800D40E0 */ .space 0x04

dlabel numLoads
/* C48E4 800D40E4 */ .space 0x04

dlabel currentEventInstance
/* C48E8 800D40E8 */ .space 0x04

dlabel currentActionScript
/* C48EC 800D40EC */ .space 0x04

dlabel EventAbortedPosition
/* C48F0 800D40F0 */ .space 0x04

/* Automatically generated and unreferenced pad */
dlabel D_800D40F4
/* C48F4 800D40F4 */ .space 0x04

dlabel WaterLevelArray
/* C48F8 800D40F8 */ .space 0x8C

dlabel CurrentPuzzleLevel
/* C4984 800D4184 */ .space 0x04

dlabel eventTimerArray
/* C4988 800D4188 */ .space 0x240

dlabel numActiveEventTimers
/* C4BC8 800D43C8 */ .space 0x04

dlabel WaitingToLoadSound
/* C4BCC 800D43CC */ .space 0x04

dlabel eventListNumInstances
/* C4BD0 800D43D0 */ .space 0x50

dlabel MoviePlayed
/* C4C20 800D4420 */ .space 0x04

dlabel MovieToPlay
/* C4C24 800D4424 */ .space 0x04

dlabel ResetSignalArray
/* C4C28 800D4428 */ .space 0x80

dlabel WaitingToLoadSFX
/* C4CA8 800D44A8 */ .space 0x04

dlabel WaitingForVoiceNumber
/* C4CAC 800D44AC */ .space 0x04

dlabel gHintSystem
/* C4CB0 800D44B0 */ .space 0x10

dlabel eventListArray
/* C4CC0 800D44C0 */ .space 0x320

dlabel circBuf
/* C4FE0 800D47E0 */ .space 0x1000

dlabel vramBlockList
/* C5FE0 800D57E0 */ .space 0x9D8

dlabel M_TrackClutUpdate
/* C69B8 800D61B8 */ .space 0x04

dlabel numOfBlocksUsed
/* C69BC 800D61BC */ .space 0x04

dlabel TerrainVramBlock
/* C69C0 800D61C0 */ .space 0x1C

dlabel usedVramBlocks
/* C69DC 800D61DC */ .space 0x04

dlabel openVramBlocks
/* C69E0 800D61E0 */ .space 0x04

dlabel TempMat.40
/* C69E4 800D61E4 */ .space 0x20

dlabel pTempMat.41
/* C6A04 800D6204 */ .space 0x04

dlabel pTempMat.46
/* C6A08 800D6208 */ .space 0x04

dlabel pTempMat.51
/* C6A0C 800D620C */ .space 0x08

dlabel TempMat.62
/* C6A14 800D6214 */ .space 0x20

dlabel pTempMat.63
/* C6A34 800D6234 */ .space 0x10

dlabel TempMat.66
/* C6A44 800D6244 */ .space 0x20

dlabel pTempMat.67
/* C6A64 800D6264 */ .space 0x04

dlabel pTempMat.72
/* C6A68 800D6268 */ .space 0x04

dlabel FireReaverFlag
/* C6A6C 800D626C */ .space 0x04

dlabel MANNA_Position
/* C6A70 800D6270 */ .space 0x02

dlabel MANNA_Pos_vel
/* C6A72 800D6272 */ .space 0x02

dlabel glyph_time
/* C6A74 800D6274 */ .space 0x02

dlabel glyph_trigger
/* C6A76 800D6276 */ .space 0x02

dlabel glyph_cost
/* C6A78 800D6278 */ .space 0x02

dlabel HUD_Count
/* C6A7A 800D627A */ .space 0x02

dlabel HUD_Count_Overall
/* C6A7C 800D627C */ .space 0x04

dlabel blast_range
/* C6A80 800D6280 */ .space 0x04

dlabel fx_radius_old
/* C6A84 800D6284 */ .space 0x04

dlabel MANNA_Pickup_Time
/* C6A88 800D6288 */ .space 0x04

dlabel HUD_Rotation
/* C6A8C 800D628C */ .space 0x02

dlabel HUD_Rot_vel
/* C6A8E 800D628E */ .space 0x02

dlabel HUD_Position
/* C6A90 800D6290 */ .space 0x02

dlabel HUD_Pos_vel
/* C6A92 800D6292 */ .space 0x02

dlabel HUD_State
/* C6A94 800D6294 */ .space 0x02

dlabel HUD_Wait
/* C6A96 800D6296 */ .space 0x02

dlabel HUD_Cap_Pos
/* C6A98 800D6298 */ .space 0x08

dlabel HUD_Cap_Vel
/* C6AA0 800D62A0 */ .space 0x08

dlabel warpDraw
/* C6AA8 800D62A8 */ .space 0x04

dlabel glowdeg
/* C6AAC 800D62AC */ .space 0x04

dlabel hud_warp_arrow_flash
/* C6AB0 800D62B0 */ .space 0x04

dlabel monsterSenseArray
/* C6AB4 800D62B4 */ .space 0xA0

dlabel monsterSensed
/* C6B54 800D6354 */ .space 0x28

dlabel lastSenseFrame
/* C6B7C 800D637C */ .space 0x04

dlabel _chanStatusBlockPool
/* C6B80 800D6380 */ .space 0x10

dlabel _segValues
/* C6B90 800D6390 */ .space 0x780

dlabel _controllerPool
/* C7310 800D6B10 */ .space 0x10

dlabel _interpStateBlockPool
/* C7320 800D6B20 */ .space 0x10

dlabel _appDataVM
/* C7330 800D6B30 */ .space 0x08

dlabel poolManagementDataStorage
/* C7338 800D6B38 */ .space 0x20

dlabel timerArray
/* C7358 800D6B58 */ .space 0x28

dlabel timerIndex
/* C7380 800D6B80 */ .space 0x04

dlabel poolManagementData
/* C7384 800D6B84 */ .space 0x04

dlabel ExternalForces
/* C7388 800D6B88 */ .space 0x04

/* Automatically generated and unreferenced pad */
dlabel D_800D6B8C
/* C738C 800D6B8C */ .space 0x0C

dlabel TempMat_dup1
/* C7398 800D6B98 */ .space 0x20

dlabel LastTime.366
/* C73B8 800D6BB8 */ .space 0x10

dlabel Raziel
/* C73C8 800D6BC8 */ .space 0x5B8

dlabel PlayerData
/* C7980 800D7180 */ .space 0x04

/* Automatically generated and unreferenced pad */
dlabel D_800D7184
/* C7984 800D7184 */ .space 0x04

dlabel razInterpInfo
/* C7988 800D7188 */ .space 0x24

/* Automatically generated and unreferenced pad */
dlabel D_800D71AC
/* C79AC 800D71AC */ .space 0x0C

dlabel constrictData
/* C79B8 800D71B8 */ .space 0x80

dlabel TempMat_dup2
/* C7A38 800D7238 */ .space 0x20

dlabel gameTracker
/* C7A58 800D7258 */ .space 0x04

dlabel PadData
/* C7A5C 800D725C */ .space 0x04

dlabel ExtraRotData
/* C7A60 800D7260 */ .space 0x06

/* Automatically generated and unreferenced pad */
dlabel D_800D7266
/* C7A66 800D7266 */ .space 0x02

dlabel ExtraRot
/* C7A68 800D7268 */ .space 0x04

/* Automatically generated and unreferenced pad */
dlabel D_800D726C
/* C7A6C 800D726C */ .space 0x0C

dlabel ExternalForces_dup1
/* C7A78 800D7278 */ .space 0x50

dlabel PhysicsMode
/* C7AC8 800D72C8 */ .space 0x10

dlabel EngagedList
/* C7AD8 800D72D8 */ .space 0x78

dlabel Norm
/* C7B50 800D7350 */ .space 0x08

dlabel LastRC
/* C7B58 800D7358 */ .space 0x04

dlabel AutoFaceAngle
/* C7B5C 800D735C */ .space 0x04

dlabel ControlFlag
/* C7B60 800D7360 */ .space 0x04

dlabel UW_angle
/* C7B64 800D7364 */ .space 0x04

dlabel UW_scalex
/* C7B68 800D7368 */ .space 0x04

dlabel UW_scalexInc
/* C7B6C 800D736C */ .space 0x04

dlabel UW_angleInc
/* C7B70 800D7370 */ .space 0x04

dlabel savedInfoTracker
/* C7B74 800D7374 */ .space 0x10

dlabel bufferSavedIntroArray
/* C7B84 800D7384 */ .space 0x100

dlabel __ra_temp
/* C7C84 800D7484 */ .space 0x04

dlabel voiceTracker
/* C7C88 800D7488 */ .space 0x128

dlabel the_language
/* C7DB0 800D75B0 */ .space 0x04

dlabel wasDualShock.54
/* C7DB4 800D75B4 */ .space 0x04

dlabel FaceButtons
/* C7DB8 800D75B8 */ .space 0x04
