.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
dlabel jtbl_80010134
/* 934 80010134 60BA0180 */ .word .L8001BA60
/* 938 80010138 88BA0180 */ .word .L8001BA88
/* 93C 8001013C 80BA0180 */ .word .L8001BA80
/* 940 80010140 88BA0180 */ .word .L8001BA88
/* 944 80010144 80BA0180 */ .word .L8001BA80
/* 948 80010148 70BA0180 */ .word .L8001BA70
/* 94C 8001014C 50BA0180 */ .word .L8001BA50
/* 950 80010150 88BA0180 */ .word .L8001BA88
/* 954 80010154 A8BA0180 */ .word .L8001BAA8
/* 958 80010158 88BA0180 */ .word .L8001BA88
/* 95C 8001015C 88BA0180 */ .word .L8001BA88
/* 960 80010160 88BA0180 */ .word .L8001BA88
/* 964 80010164 60BA0180 */ .word .L8001BA60
/* 968 80010168 60BA0180 */ .word .L8001BA60
/* 96C 8001016C 88BA0180 */ .word .L8001BA88
/* 970 80010170 A8BA0180 */ .word .L8001BAA8
.size jtbl_80010134, . - jtbl_80010134


.section .text
/* Generated by spimdisasm 1.21.0 */

glabel CAMERA_Process
/* C06C 8001B86C E8FFBD27 */  addiu      $sp, $sp, -0x18
/* C070 8001B870 1000B0AF */  sw         $s0, 0x10($sp)
/* C074 8001B874 21808000 */  addu       $s0, $a0, $zero
/* C078 8001B878 1400BFAF */  sw         $ra, 0x14($sp)
/* C07C 8001B87C 0801058E */  lw         $a1, 0x108($s0)
/* C080 8001B880 16010396 */  lhu        $v1, 0x116($s0)
/* C084 8001B884 6800A494 */  lhu        $a0, 0x68($a1)
/* C088 8001B888 BA040296 */  lhu        $v0, 0x4BA($s0)
/* C08C 8001B88C 23186400 */  subu       $v1, $v1, $a0
/* C090 8001B890 23104300 */  subu       $v0, $v0, $v1
/* C094 8001B894 BA0402A6 */  sh         $v0, 0x4BA($s0)
/* C098 8001B898 1501088A */  lwl        $t0, 0x115($s0)
/* C09C 8001B89C 1201089A */  lwr        $t0, 0x112($s0)
/* C0A0 8001B8A0 16010986 */  lh         $t1, 0x116($s0)
/* C0A4 8001B8A4 0F0108AA */  swl        $t0, 0x10F($s0)
/* C0A8 8001B8A8 0C0108BA */  swr        $t0, 0x10C($s0)
/* C0AC 8001B8AC 100109A6 */  sh         $t1, 0x110($s0)
/* C0B0 8001B8B0 5F00A888 */  lwl        $t0, 0x5F($a1)
/* C0B4 8001B8B4 5C00A898 */  lwr        $t0, 0x5C($a1)
/* C0B8 8001B8B8 6000A984 */  lh         $t1, 0x60($a1)
/* C0BC 8001B8BC 150108AA */  swl        $t0, 0x115($s0)
/* C0C0 8001B8C0 120108BA */  swr        $t0, 0x112($s0)
/* C0C4 8001B8C4 160109A6 */  sh         $t1, 0x116($s0)
/* C0C8 8001B8C8 2301088A */  lwl        $t0, 0x123($s0)
/* C0CC 8001B8CC 2001089A */  lwr        $t0, 0x120($s0)
/* C0D0 8001B8D0 2701098A */  lwl        $t1, 0x127($s0)
/* C0D4 8001B8D4 2401099A */  lwr        $t1, 0x124($s0)
/* C0D8 8001B8D8 1B0108AA */  swl        $t0, 0x11B($s0)
/* C0DC 8001B8DC 180108BA */  swr        $t0, 0x118($s0)
/* C0E0 8001B8E0 1F0109AA */  swl        $t1, 0x11F($s0)
/* C0E4 8001B8E4 1C0109BA */  swr        $t1, 0x11C($s0)
/* C0E8 8001B8E8 7700A888 */  lwl        $t0, 0x77($a1)
/* C0EC 8001B8EC 7400A898 */  lwr        $t0, 0x74($a1)
/* C0F0 8001B8F0 7B00A988 */  lwl        $t1, 0x7B($a1)
/* C0F4 8001B8F4 7800A998 */  lwr        $t1, 0x78($a1)
/* C0F8 8001B8F8 230108AA */  swl        $t0, 0x123($s0)
/* C0FC 8001B8FC 200108BA */  swr        $t0, 0x120($s0)
/* C100 8001B900 270109AA */  swl        $t1, 0x127($s0)
/* C104 8001B904 240109BA */  swr        $t1, 0x124($s0)
/* C108 8001B908 F803038E */  lw         $v1, 0x3F8($s0)
/* C10C 8001B90C 0000028E */  lw         $v0, 0x0($s0)
/* C110 8001B910 00000000 */  nop
/* C114 8001B914 09006214 */  bne        $v1, $v0, .L8001B93C
/* C118 8001B918 00000000 */   nop
/* C11C 8001B91C FC030386 */  lh         $v1, 0x3FC($s0)
/* C120 8001B920 04000286 */  lh         $v0, 0x4($s0)
/* C124 8001B924 00000000 */  nop
/* C128 8001B928 04006214 */  bne        $v1, $v0, .L8001B93C
/* C12C 8001B92C 01000224 */   addiu     $v0, $zero, 0x1
/* C130 8001B930 488E82A7 */  sh         $v0, %gp_rel(camera_still)($gp)
/* C134 8001B934 506E0008 */  j          .L8001B940
/* C138 8001B938 00000000 */   nop
.L8001B93C:
/* C13C 8001B93C 488E80A7 */  sh         $zero, %gp_rel(camera_still)($gp)
.L8001B940:
/* C140 8001B940 0300088A */  lwl        $t0, 0x3($s0)
/* C144 8001B944 0000089A */  lwr        $t0, 0x0($s0)
/* C148 8001B948 04000986 */  lh         $t1, 0x4($s0)
/* C14C 8001B94C FB0308AA */  swl        $t0, 0x3FB($s0)
/* C150 8001B950 F80308BA */  swr        $t0, 0x3F8($s0)
/* C154 8001B954 FC0309A6 */  sh         $t1, 0x3FC($s0)
/* C158 8001B958 9C04028E */  lw         $v0, 0x49C($s0)
/* C15C 8001B95C 21200002 */  addu       $a0, $s0, $zero
/* C160 8001B960 B80400A6 */  sh         $zero, 0x4B8($s0)
/* C164 8001B964 E659000C */  jal        CAMERA_QueryMode
/* C168 8001B968 980402AE */   sw        $v0, 0x498($s0)
/* C16C 8001B96C 12010426 */  addiu      $a0, $s0, 0x112
/* C170 8001B970 0C010626 */  addiu      $a2, $s0, 0x10C
/* C174 8001B974 9C0402AE */  sw         $v0, 0x49C($s0)
/* C178 8001B978 12010296 */  lhu        $v0, 0x112($s0)
/* C17C 8001B97C 02008394 */  lhu        $v1, 0x2($a0)
/* C180 8001B980 04008494 */  lhu        $a0, 0x4($a0)
/* C184 8001B984 0C010596 */  lhu        $a1, 0x10C($s0)
/* C188 8001B988 0200C794 */  lhu        $a3, 0x2($a2)
/* C18C 8001B98C 0400C694 */  lhu        $a2, 0x4($a2)
/* C190 8001B990 23104500 */  subu       $v0, $v0, $a1
/* C194 8001B994 280102A6 */  sh         $v0, 0x128($s0)
/* C198 8001B998 28010226 */  addiu      $v0, $s0, 0x128
/* C19C 8001B99C 23186700 */  subu       $v1, $v1, $a3
/* C1A0 8001B9A0 23208600 */  subu       $a0, $a0, $a2
/* C1A4 8001B9A4 020043A4 */  sh         $v1, 0x2($v0)
/* C1A8 8001B9A8 040044A4 */  sh         $a0, 0x4($v0)
/* C1AC 8001B9AC 28010286 */  lh         $v0, 0x128($s0)
/* C1B0 8001B9B0 00000000 */  nop
/* C1B4 8001B9B4 18004200 */  mult       $v0, $v0
/* C1B8 8001B9B8 12180000 */  mflo       $v1
/* C1BC 8001B9BC 2A010286 */  lh         $v0, 0x12A($s0)
/* C1C0 8001B9C0 00000000 */  nop
/* C1C4 8001B9C4 18004200 */  mult       $v0, $v0
/* C1C8 8001B9C8 A004028E */  lw         $v0, 0x4A0($s0)
/* C1CC 8001B9CC 00000000 */  nop
/* C1D0 8001B9D0 A40402AE */  sw         $v0, 0x4A4($s0)
/* C1D4 8001B9D4 12280000 */  mflo       $a1
/* C1D8 8001B9D8 A6E7000C */  jal        MATH3D_FastSqrt0
/* C1DC 8001B9DC 21206500 */   addu      $a0, $v1, $a1
/* C1E0 8001B9E0 468E8387 */  lh         $v1, %gp_rel(shorten_flag)($gp)
/* C1E4 8001B9E4 00000000 */  nop
/* C1E8 8001B9E8 02006014 */  bnez       $v1, .L8001B9F4
/* C1EC 8001B9EC A00402AE */   sw        $v0, 0x4A0($s0)
/* C1F0 8001B9F0 448E80A7 */  sh         $zero, %gp_rel(shorten_count)($gp)
.L8001B9F4:
/* C1F4 8001B9F4 8404028E */  lw         $v0, 0x484($s0)
/* C1F8 8001B9F8 468E80A7 */  sh         $zero, %gp_rel(shorten_flag)($gp)
/* C1FC 8001B9FC 02004018 */  blez       $v0, .L8001BA08
/* C200 8001BA00 FFFF4224 */   addiu     $v0, $v0, -0x1
/* C204 8001BA04 840402AE */  sw         $v0, 0x484($s0)
.L8001BA08:
/* C208 8001BA08 F0000386 */  lh         $v1, 0xF0($s0)
/* C20C 8001BA0C 06000224 */  addiu      $v0, $zero, 0x6
/* C210 8001BA10 06006210 */  beq        $v1, $v0, .L8001BA2C
/* C214 8001BA14 1000622C */   sltiu     $v0, $v1, 0x10
/* C218 8001BA18 2463000C */  jal        CAMERA_HandleTransitions
/* C21C 8001BA1C 21200002 */   addu      $a0, $s0, $zero
/* C220 8001BA20 F0000386 */  lh         $v1, 0xF0($s0)
/* C224 8001BA24 00000000 */  nop
/* C228 8001BA28 1000622C */  sltiu      $v0, $v1, 0x10
.L8001BA2C:
/* C22C 8001BA2C 16004010 */  beqz       $v0, .L8001BA88
/* C230 8001BA30 0180023C */   lui       $v0, %hi(jtbl_80010134)
/* C234 8001BA34 34014224 */  addiu      $v0, $v0, %lo(jtbl_80010134)
/* C238 8001BA38 80180300 */  sll        $v1, $v1, 2
/* C23C 8001BA3C 21186200 */  addu       $v1, $v1, $v0
/* C240 8001BA40 0000628C */  lw         $v0, 0x0($v1)
/* C244 8001BA44 00000000 */  nop
/* C248 8001BA48 08004000 */  jr         $v0
/* C24C 8001BA4C 00000000 */   nop
.L8001BA50:
/* C250 8001BA50 7162000C */  jal        CAMERA_LookProcess
/* C254 8001BA54 21200002 */   addu      $a0, $s0, $zero
/* C258 8001BA58 A36E0008 */  j          .L8001BA8C
/* C25C 8001BA5C 21200002 */   addu      $a0, $s0, $zero
.L8001BA60:
/* C260 8001BA60 DA67000C */  jal        CAMERA_GenericCameraProcess
/* C264 8001BA64 21200002 */   addu      $a0, $s0, $zero
/* C268 8001BA68 A36E0008 */  j          .L8001BA8C
/* C26C 8001BA6C 21200002 */   addu      $a0, $s0, $zero
.L8001BA70:
/* C270 8001BA70 F968000C */  jal        CAMERA_CinematicProcess
/* C274 8001BA74 21200002 */   addu      $a0, $s0, $zero
/* C278 8001BA78 A36E0008 */  j          .L8001BA8C
/* C27C 8001BA7C 21200002 */   addu      $a0, $s0, $zero
.L8001BA80:
/* C280 8001BA80 0C6D000C */  jal        CAMERA_SplineProcess
/* C284 8001BA84 21200002 */   addu      $a0, $s0, $zero
.L8001BA88:
/* C288 8001BA88 21200002 */  addu       $a0, $s0, $zero
.L8001BA8C:
/* C28C 8001BA8C E800828C */  lw         $v0, 0xE8($a0)
/* C290 8001BA90 FFF70324 */  addiu      $v1, $zero, -0x801
/* C294 8001BA94 24104300 */  and        $v0, $v0, $v1
/* C298 8001BA98 FFEF0324 */  addiu      $v1, $zero, -0x1001
/* C29C 8001BA9C 24104300 */  and        $v0, $v0, $v1
/* C2A0 8001BAA0 E16D000C */  jal        CAMERA_ShakeCamera
/* C2A4 8001BAA4 E80082AC */   sw        $v0, 0xE8($a0)
.L8001BAA8:
/* C2A8 8001BAA8 1400BF8F */  lw         $ra, 0x14($sp)
/* C2AC 8001BAAC 1000B08F */  lw         $s0, 0x10($sp)
/* C2B0 8001BAB0 0800E003 */  jr         $ra
/* C2B4 8001BAB4 1800BD27 */   addiu     $sp, $sp, 0x18
.size CAMERA_Process, . - CAMERA_Process
