.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_80011DA8
/* 25A8 80011DA8 ACCF0680 */ .word .L8006CFAC
/* 25AC 80011DAC BCCF0680 */ .word .L8006CFBC
/* 25B0 80011DB0 C4CF0680 */ .word .L8006CFC4
/* 25B4 80011DB4 C4CF0680 */ .word .L8006CFC4
/* 25B8 80011DB8 BCCF0680 */ .word .L8006CFBC
/* 25BC 80011DBC DCCF0680 */ .word .L8006CFDC
/* 25C0 80011DC0 D4CF0680 */ .word .L8006CFD4
.size jtbl_80011DA8, . - jtbl_80011DA8


.section .text
/* Generated by spimdisasm 1.21.0 */

glabel PhysicalObjectPost
/* 5D148 8006C948 D0FFBD27 */  addiu      $sp, $sp, -0x30
/* 5D14C 8006C94C 2800B4AF */  sw         $s4, 0x28($sp)
/* 5D150 8006C950 21A08000 */  addu       $s4, $a0, $zero
/* 5D154 8006C954 1800B0AF */  sw         $s0, 0x18($sp)
/* 5D158 8006C958 2180A000 */  addu       $s0, $a1, $zero
/* 5D15C 8006C95C 2400B3AF */  sw         $s3, 0x24($sp)
/* 5D160 8006C960 2198C000 */  addu       $s3, $a2, $zero
/* 5D164 8006C964 8000023C */  lui        $v0, (0x800010 >> 16)
/* 5D168 8006C968 10004234 */  ori        $v0, $v0, (0x800010 & 0xFFFF)
/* 5D16C 8006C96C 2000B2AF */  sw         $s2, 0x20($sp)
/* 5D170 8006C970 2C00BFAF */  sw         $ra, 0x2C($sp)
/* 5D174 8006C974 1C00B1AF */  sw         $s1, 0x1C($sp)
/* 5D178 8006C978 6C01918E */  lw         $s1, 0x16C($s4)
/* 5D17C 8006C97C D6000212 */  beq        $s0, $v0, .L8006CCD8
/* 5D180 8006C980 21906002 */   addu      $s2, $s3, $zero
/* 5D184 8006C984 2B105000 */  sltu       $v0, $v0, $s0
/* 5D188 8006C988 4A004014 */  bnez       $v0, .L8006CAB4
/* 5D18C 8006C98C 8000023C */   lui       $v0, (0x800027 >> 16)
/* 5D190 8006C990 2000023C */  lui        $v0, (0x200003 >> 16)
/* 5D194 8006C994 03004234 */  ori        $v0, $v0, (0x200003 & 0xFFFF)
/* 5D198 8006C998 BC010212 */  beq        $s0, $v0, .L8006D08C
/* 5D19C 8006C99C 2B105000 */   sltu      $v0, $v0, $s0
/* 5D1A0 8006C9A0 20004014 */  bnez       $v0, .L8006CA24
/* 5D1A4 8006C9A4 8000023C */   lui       $v0, (0x800001 >> 16)
/* 5D1A8 8006C9A8 0800023C */  lui        $v0, (0x80005 >> 16)
/* 5D1AC 8006C9AC 05004234 */  ori        $v0, $v0, (0x80005 & 0xFFFF)
/* 5D1B0 8006C9B0 E5010212 */  beq        $s0, $v0, .L8006D148
/* 5D1B4 8006C9B4 2B105000 */   sltu      $v0, $v0, $s0
/* 5D1B8 8006C9B8 0A004014 */  bnez       $v0, .L8006C9E4
/* 5D1BC 8006C9BC 1000023C */   lui       $v0, (0x100008 >> 16)
/* 5D1C0 8006C9C0 0400023C */  lui        $v0, (0x40002 >> 16)
/* 5D1C4 8006C9C4 02004234 */  ori        $v0, $v0, (0x40002 & 0xFFFF)
/* 5D1C8 8006C9C8 E4010212 */  beq        $s0, $v0, .L8006D15C
/* 5D1CC 8006C9CC 0400023C */   lui       $v0, (0x4000E >> 16)
/* 5D1D0 8006C9D0 0E004234 */  ori        $v0, $v0, (0x4000E & 0xFFFF)
/* 5D1D4 8006C9D4 FB010212 */  beq        $s0, $v0, .L8006D1C4
/* 5D1D8 8006C9D8 00000000 */   nop
/* 5D1DC 8006C9DC 86B40108 */  j          .L8006D218
/* 5D1E0 8006C9E0 00000000 */   nop
.L8006C9E4:
/* 5D1E4 8006C9E4 08004234 */  ori        $v0, $v0, (0x100008 & 0xFFFF)
/* 5D1E8 8006C9E8 4D010212 */  beq        $s0, $v0, .L8006CF20
/* 5D1EC 8006C9EC 2B105000 */   sltu      $v0, $v0, $s0
/* 5D1F0 8006C9F0 07004014 */  bnez       $v0, .L8006CA10
/* 5D1F4 8006C9F4 2000023C */   lui       $v0, (0x200002 >> 16)
/* 5D1F8 8006C9F8 1000023C */  lui        $v0, (0x100007 >> 16)
/* 5D1FC 8006C9FC 07004234 */  ori        $v0, $v0, (0x100007 & 0xFFFF)
/* 5D200 8006CA00 F8000212 */  beq        $s0, $v0, .L8006CDE4
/* 5D204 8006CA04 EFFF033C */   lui       $v1, (0xFFEFF7FF >> 16)
/* 5D208 8006CA08 86B40108 */  j          .L8006D218
/* 5D20C 8006CA0C 00000000 */   nop
.L8006CA10:
/* 5D210 8006CA10 02004234 */  ori        $v0, $v0, (0x200002 & 0xFFFF)
/* 5D214 8006CA14 99010212 */  beq        $s0, $v0, .L8006D07C
/* 5D218 8006CA18 21208002 */   addu      $a0, $s4, $zero
/* 5D21C 8006CA1C 86B40108 */  j          .L8006D218
/* 5D220 8006CA20 00000000 */   nop
.L8006CA24:
/* 5D224 8006CA24 01004234 */  ori        $v0, $v0, (0x800001 & 0xFFFF)
/* 5D228 8006CA28 6A000212 */  beq        $s0, $v0, .L8006CBD4
/* 5D22C 8006CA2C 2B105000 */   sltu      $v0, $v0, $s0
/* 5D230 8006CA30 11004014 */  bnez       $v0, .L8006CA78
/* 5D234 8006CA34 8000023C */   lui       $v0, (0x800004 >> 16)
/* 5D238 8006CA38 2000023C */  lui        $v0, (0x200006 >> 16)
/* 5D23C 8006CA3C 06004234 */  ori        $v0, $v0, (0x200006 & 0xFFFF)
/* 5D240 8006CA40 9C010212 */  beq        $s0, $v0, .L8006D0B4
/* 5D244 8006CA44 2B105000 */   sltu      $v0, $v0, $s0
/* 5D248 8006CA48 07004014 */  bnez       $v0, .L8006CA68
/* 5D24C 8006CA4C 8000023C */   lui       $v0, (0x800000 >> 16)
/* 5D250 8006CA50 2000023C */  lui        $v0, (0x200005 >> 16)
/* 5D254 8006CA54 05004234 */  ori        $v0, $v0, (0x200005 & 0xFFFF)
/* 5D258 8006CA58 91010212 */  beq        $s0, $v0, .L8006D0A0
/* 5D25C 8006CA5C 0001033C */   lui       $v1, (0x1000000 >> 16)
/* 5D260 8006CA60 86B40108 */  j          .L8006D218
/* 5D264 8006CA64 00000000 */   nop
.L8006CA68:
/* 5D268 8006CA68 49000212 */  beq        $s0, $v0, .L8006CB90
/* 5D26C 8006CA6C 00000000 */   nop
/* 5D270 8006CA70 86B40108 */  j          .L8006D218
/* 5D274 8006CA74 00000000 */   nop
.L8006CA78:
/* 5D278 8006CA78 04004234 */  ori        $v0, $v0, (0x800004 & 0xFFFF)
/* 5D27C 8006CA7C 8A000212 */  beq        $s0, $v0, .L8006CCA8
/* 5D280 8006CA80 2B105000 */   sltu      $v0, $v0, $s0
/* 5D284 8006CA84 06004014 */  bnez       $v0, .L8006CAA0
/* 5D288 8006CA88 8000023C */   lui       $v0, (0x800002 >> 16)
/* 5D28C 8006CA8C 02004234 */  ori        $v0, $v0, (0x800002 & 0xFFFF)
/* 5D290 8006CA90 5F000212 */  beq        $s0, $v0, .L8006CC10
/* 5D294 8006CA94 00000000 */   nop
/* 5D298 8006CA98 86B40108 */  j          .L8006D218
/* 5D29C 8006CA9C 00000000 */   nop
.L8006CAA0:
/* 5D2A0 8006CAA0 08004234 */  ori        $v0, $v0, (0x800008 & 0xFFFF)
/* 5D2A4 8006CAA4 84000212 */  beq        $s0, $v0, .L8006CCB8
/* 5D2A8 8006CAA8 21208002 */   addu      $a0, $s4, $zero
/* 5D2AC 8006CAAC 86B40108 */  j          .L8006D218
/* 5D2B0 8006CAB0 00000000 */   nop
.L8006CAB4:
/* 5D2B4 8006CAB4 27004234 */  ori        $v0, $v0, (0x800027 & 0xFFFF)
/* 5D2B8 8006CAB8 63010212 */  beq        $s0, $v0, .L8006D048
/* 5D2BC 8006CABC 2B105000 */   sltu      $v0, $v0, $s0
/* 5D2C0 8006CAC0 19004014 */  bnez       $v0, .L8006CB28
/* 5D2C4 8006CAC4 8000023C */   lui       $v0, (0x800022 >> 16)
/* 5D2C8 8006CAC8 22004234 */  ori        $v0, $v0, (0x800022 & 0xFFFF)
/* 5D2CC 8006CACC 2B105000 */  sltu       $v0, $v0, $s0
/* 5D2D0 8006CAD0 0B004014 */  bnez       $v0, .L8006CB00
/* 5D2D4 8006CAD4 8000023C */   lui       $v0, (0x800025 >> 16)
/* 5D2D8 8006CAD8 8000123C */  lui        $s2, (0x800021 >> 16)
/* 5D2DC 8006CADC 21005236 */  ori        $s2, $s2, (0x800021 & 0xFFFF)
/* 5D2E0 8006CAE0 2B101202 */  sltu       $v0, $s0, $s2
/* 5D2E4 8006CAE4 98004010 */  beqz       $v0, .L8006CD48
/* 5D2E8 8006CAE8 8000023C */   lui       $v0, (0x800020 >> 16)
/* 5D2EC 8006CAEC 20004234 */  ori        $v0, $v0, (0x800020 & 0xFFFF)
/* 5D2F0 8006CAF0 7E000212 */  beq        $s0, $v0, .L8006CCEC
/* 5D2F4 8006CAF4 00000000 */   nop
/* 5D2F8 8006CAF8 86B40108 */  j          .L8006D218
/* 5D2FC 8006CAFC 00000000 */   nop
.L8006CB00:
/* 5D300 8006CB00 25004234 */  ori        $v0, $v0, (0x800025 & 0xFFFF)
/* 5D304 8006CB04 C4010212 */  beq        $s0, $v0, .L8006D218
/* 5D308 8006CB08 2B105000 */   sltu      $v0, $v0, $s0
/* 5D30C 8006CB0C 16014014 */  bnez       $v0, .L8006CF68
/* 5D310 8006CB10 8000023C */   lui       $v0, (0x800023 >> 16)
/* 5D314 8006CB14 23004234 */  ori        $v0, $v0, (0x800023 & 0xFFFF)
/* 5D318 8006CB18 7C000212 */  beq        $s0, $v0, .L8006CD0C
/* 5D31C 8006CB1C 00000000 */   nop
/* 5D320 8006CB20 86B40108 */  j          .L8006D218
/* 5D324 8006CB24 00000000 */   nop
.L8006CB28:
/* 5D328 8006CB28 2C004234 */  ori        $v0, $v0, (0x80002C & 0xFFFF)
/* 5D32C 8006CB2C 50010212 */  beq        $s0, $v0, .L8006D070
/* 5D330 8006CB30 2B105000 */   sltu      $v0, $v0, $s0
/* 5D334 8006CB34 0C004014 */  bnez       $v0, .L8006CB68
/* 5D338 8006CB38 8000023C */   lui       $v0, (0x80002A >> 16)
/* 5D33C 8006CB3C 2A004234 */  ori        $v0, $v0, (0x80002A & 0xFFFF)
/* 5D340 8006CB40 8B010212 */  beq        $s0, $v0, .L8006D170
/* 5D344 8006CB44 2B105000 */   sltu      $v0, $v0, $s0
/* 5D348 8006CB48 5B014014 */  bnez       $v0, .L8006D0B8
/* 5D34C 8006CB4C 7FFF033C */   lui       $v1, (0xFF7FFFFF >> 16)
/* 5D350 8006CB50 8000023C */  lui        $v0, (0x800029 >> 16)
/* 5D354 8006CB54 29004234 */  ori        $v0, $v0, (0x800029 & 0xFFFF)
/* 5D358 8006CB58 5C010212 */  beq        $s0, $v0, .L8006D0CC
/* 5D35C 8006CB5C 00000000 */   nop
/* 5D360 8006CB60 86B40108 */  j          .L8006D218
/* 5D364 8006CB64 00000000 */   nop
.L8006CB68:
/* 5D368 8006CB68 2E004234 */  ori        $v0, $v0, (0x80002E & 0xFFFF)
/* 5D36C 8006CB6C 46000212 */  beq        $s0, $v0, .L8006CC88
/* 5D370 8006CB70 2B100202 */   sltu      $v0, $s0, $v0
/* 5D374 8006CB74 61004014 */  bnez       $v0, .L8006CCFC
/* 5D378 8006CB78 0008023C */   lui       $v0, (0x8000008 >> 16)
/* 5D37C 8006CB7C 08004234 */  ori        $v0, $v0, (0x8000008 & 0xFFFF)
/* 5D380 8006CB80 83010212 */  beq        $s0, $v0, .L8006D190
/* 5D384 8006CB84 21208002 */   addu      $a0, $s4, $zero
/* 5D388 8006CB88 86B40108 */  j          .L8006D218
/* 5D38C 8006CB8C 00000000 */   nop
.L8006CB90:
/* 5D390 8006CB90 9266010C */  jal        STREAM_IsMorphInProgress
/* 5D394 8006CB94 00000000 */   nop
/* 5D398 8006CB98 05004014 */  bnez       $v0, .L8006CBB0
/* 5D39C 8006CB9C 00000000 */   nop
/* 5D3A0 8006CBA0 D2BD8287 */  lh         $v0, %gp_rel(gameTrackerX + 0xA)($gp)
/* 5D3A4 8006CBA4 00000000 */  nop
/* 5D3A8 8006CBA8 9B014014 */  bnez       $v0, .L8006D218
/* 5D3AC 8006CBAC 00000000 */   nop
.L8006CBB0:
/* 5D3B0 8006CBB0 00004586 */  lh         $a1, 0x0($s2)
/* 5D3B4 8006CBB4 02004686 */  lh         $a2, 0x2($s2)
/* 5D3B8 8006CBB8 04004786 */  lh         $a3, 0x4($s2)
/* 5D3BC 8006CBBC 0800428E */  lw         $v0, 0x8($s2)
/* 5D3C0 8006CBC0 21208002 */  addu       $a0, $s4, $zero
/* 5D3C4 8006CBC4 DDA5010C */  jal        PushPhysOb
/* 5D3C8 8006CBC8 1000A2AF */   sw        $v0, 0x10($sp)
/* 5D3CC 8006CBCC 86B40108 */  j          .L8006D218
/* 5D3D0 8006CBD0 0C0042AE */   sw        $v0, 0xC($s2)
.L8006CBD4:
/* 5D3D4 8006CBD4 9266010C */  jal        STREAM_IsMorphInProgress
/* 5D3D8 8006CBD8 00000000 */   nop
/* 5D3DC 8006CBDC 05004014 */  bnez       $v0, .L8006CBF4
/* 5D3E0 8006CBE0 00000000 */   nop
/* 5D3E4 8006CBE4 D2BD8287 */  lh         $v0, %gp_rel(gameTrackerX + 0xA)($gp)
/* 5D3E8 8006CBE8 00000000 */  nop
/* 5D3EC 8006CBEC 8A014014 */  bnez       $v0, .L8006D218
/* 5D3F0 8006CBF0 00000000 */   nop
.L8006CBF4:
/* 5D3F4 8006CBF4 00006586 */  lh         $a1, 0x0($s3)
/* 5D3F8 8006CBF8 02006686 */  lh         $a2, 0x2($s3)
/* 5D3FC 8006CBFC 0800678E */  lw         $a3, 0x8($s3)
/* 5D400 8006CC00 54A9010C */  jal        FlipPhysOb
/* 5D404 8006CC04 21208002 */   addu      $a0, $s4, $zero
/* 5D408 8006CC08 86B40108 */  j          .L8006D218
/* 5D40C 8006CC0C 0C0062AE */   sw        $v0, 0xC($s3)
.L8006CC10:
/* 5D410 8006CC10 9266010C */  jal        STREAM_IsMorphInProgress
/* 5D414 8006CC14 00000000 */   nop
/* 5D418 8006CC18 09004014 */  bnez       $v0, .L8006CC40
/* 5D41C 8006CC1C 00000000 */   nop
/* 5D420 8006CC20 D2BD8287 */  lh         $v0, %gp_rel(gameTrackerX + 0xA)($gp)
/* 5D424 8006CC24 00000000 */  nop
/* 5D428 8006CC28 05004010 */  beqz       $v0, .L8006CC40
/* 5D42C 8006CC2C 00000000 */   nop
/* 5D430 8006CC30 04006286 */  lh         $v0, 0x4($s3)
/* 5D434 8006CC34 00000000 */  nop
/* 5D438 8006CC38 77014014 */  bnez       $v0, .L8006D218
/* 5D43C 8006CC3C 00000000 */   nop
.L8006CC40:
/* 5D440 8006CC40 04004586 */  lh         $a1, 0x4($s2)
/* 5D444 8006CC44 0800468E */  lw         $a2, 0x8($s2)
/* 5D448 8006CC48 06004786 */  lh         $a3, 0x6($s2)
/* 5D44C 8006CC4C 0BAA010C */  jal        PickUpPhysOb
/* 5D450 8006CC50 21208002 */   addu      $a0, $s4, $zero
/* 5D454 8006CC54 04004386 */  lh         $v1, 0x4($s2)
/* 5D458 8006CC58 00000000 */  nop
/* 5D45C 8006CC5C 6E016014 */  bnez       $v1, .L8006D218
/* 5D460 8006CC60 060042A6 */   sh        $v0, 0x6($s2)
/* 5D464 8006CC64 0000228E */  lw         $v0, 0x0($s1)
/* 5D468 8006CC68 00000000 */  nop
/* 5D46C 8006CC6C 00404230 */  andi       $v0, $v0, 0x4000
/* 5D470 8006CC70 69014010 */  beqz       $v0, .L8006D218
/* 5D474 8006CC74 00000000 */   nop
/* 5D478 8006CC78 75BE010C */  jal        ExecuteGravitate
/* 5D47C 8006CC7C 21208002 */   addu      $a0, $s4, $zero
/* 5D480 8006CC80 86B40108 */  j          .L8006D218
/* 5D484 8006CC84 00000000 */   nop
.L8006CC88:
/* 5D488 8006CC88 0800658E */  lw         $a1, 0x8($s3)
/* 5D48C 8006CC8C 06006686 */  lh         $a2, 0x6($s3)
/* 5D490 8006CC90 A5A9010C */  jal        CanBePickedUp
/* 5D494 8006CC94 21208002 */   addu      $a0, $s4, $zero
/* 5D498 8006CC98 5F014010 */  beqz       $v0, .L8006D218
/* 5D49C 8006CC9C 00000000 */   nop
/* 5D4A0 8006CCA0 86B40108 */  j          .L8006D218
/* 5D4A4 8006CCA4 060060A6 */   sh        $zero, 0x6($s3)
.L8006CCA8:
/* 5D4A8 8006CCA8 DBAB010C */  jal        StopPhysOb
/* 5D4AC 8006CCAC 21208002 */   addu      $a0, $s4, $zero
/* 5D4B0 8006CCB0 86B40108 */  j          .L8006D218
/* 5D4B4 8006CCB4 00000000 */   nop
.L8006CCB8:
/* 5D4B8 8006CCB8 8EC1010C */  jal        DropPhysOb
/* 5D4BC 8006CCBC 21286002 */   addu      $a1, $s3, $zero
/* 5D4C0 8006CCC0 01006232 */  andi       $v0, $s3, 0x1
/* 5D4C4 8006CCC4 54014010 */  beqz       $v0, .L8006D218
/* 5D4C8 8006CCC8 0002033C */   lui       $v1, (0x2000000 >> 16)
/* 5D4CC 8006CCCC 0000228E */  lw         $v0, 0x0($s1)
/* 5D4D0 8006CCD0 2BB40108 */  j          .L8006D0AC
/* 5D4D4 8006CCD4 25104300 */   or        $v0, $v0, $v1
.L8006CCD8:
/* 5D4D8 8006CCD8 21208002 */  addu       $a0, $s4, $zero
/* 5D4DC 8006CCDC E5A4010C */  jal        ThrowPhysOb
/* 5D4E0 8006CCE0 21286002 */   addu      $a1, $s3, $zero
/* 5D4E4 8006CCE4 86B40108 */  j          .L8006D218
/* 5D4E8 8006CCE8 00000000 */   nop
.L8006CCEC:
/* 5D4EC 8006CCEC 5AA6010C */  jal        SwitchPhysOb
/* 5D4F0 8006CCF0 21208002 */   addu      $a0, $s4, $zero
/* 5D4F4 8006CCF4 86B40108 */  j          .L8006D218
/* 5D4F8 8006CCF8 00000000 */   nop
.L8006CCFC:
/* 5D4FC 8006CCFC 34A6010C */  jal        ResetSwitchPhysOb
/* 5D500 8006CD00 21208002 */   addu      $a0, $s4, $zero
/* 5D504 8006CD04 86B40108 */  j          .L8006D218
/* 5D508 8006CD08 00000000 */   nop
.L8006CD0C:
/* 5D50C 8006CD0C 9266010C */  jal        STREAM_IsMorphInProgress
/* 5D510 8006CD10 00000000 */   nop
/* 5D514 8006CD14 05004014 */  bnez       $v0, .L8006CD2C
/* 5D518 8006CD18 00000000 */   nop
/* 5D51C 8006CD1C D2BD8287 */  lh         $v0, %gp_rel(gameTrackerX + 0xA)($gp)
/* 5D520 8006CD20 00000000 */  nop
/* 5D524 8006CD24 3C014014 */  bnez       $v0, .L8006D218
/* 5D528 8006CD28 00000000 */   nop
.L8006CD2C:
/* 5D52C 8006CD2C 0000658E */  lw         $a1, 0x0($s3)
/* 5D530 8006CD30 04006696 */  lhu        $a2, 0x4($s3)
/* 5D534 8006CD34 0E006796 */  lhu        $a3, 0xE($s3)
/* 5D538 8006CD38 D1A6010C */  jal        InteractPhysOb
/* 5D53C 8006CD3C 21208002 */   addu      $a0, $s4, $zero
/* 5D540 8006CD40 86B40108 */  j          .L8006D218
/* 5D544 8006CD44 00000000 */   nop
.L8006CD48:
/* 5D548 8006CD48 A5A3010C */  jal        CheckPhysOb
/* 5D54C 8006CD4C 21208002 */   addu      $a0, $s4, $zero
/* 5D550 8006CD50 31014010 */  beqz       $v0, .L8006D218
/* 5D554 8006CD54 21208002 */   addu      $a0, $s4, $zero
/* 5D558 8006CD58 2400918E */  lw         $s1, 0x24($s4)
/* 5D55C 8006CD5C CFA3010C */  jal        CheckPhysObFamily
/* 5D560 8006CD60 02000524 */   addiu     $a1, $zero, 0x2
/* 5D564 8006CD64 0E004010 */  beqz       $v0, .L8006CDA0
/* 5D568 8006CD68 00000000 */   nop
/* 5D56C 8006CD6C 6C01848E */  lw         $a0, 0x16C($s4)
/* 5D570 8006CD70 06001216 */  bne        $s0, $s2, .L8006CD8C
/* 5D574 8006CD74 00000000 */   nop
/* 5D578 8006CD78 04008294 */  lhu        $v0, 0x4($a0)
/* 5D57C 8006CD7C 00000000 */  nop
/* 5D580 8006CD80 02004234 */  ori        $v0, $v0, 0x2
/* 5D584 8006CD84 86B40108 */  j          .L8006D218
/* 5D588 8006CD88 040082A4 */   sh        $v0, 0x4($a0)
.L8006CD8C:
/* 5D58C 8006CD8C 04008294 */  lhu        $v0, 0x4($a0)
/* 5D590 8006CD90 00000000 */  nop
/* 5D594 8006CD94 FDFF4230 */  andi       $v0, $v0, 0xFFFD
/* 5D598 8006CD98 86B40108 */  j          .L8006D218
/* 5D59C 8006CD9C 040082A4 */   sh        $v0, 0x4($a0)
.L8006CDA0:
/* 5D5A0 8006CDA0 0A002286 */  lh         $v0, 0xA($s1)
/* 5D5A4 8006CDA4 00000000 */  nop
/* 5D5A8 8006CDA8 1B014014 */  bnez       $v0, .L8006D218
/* 5D5AC 8006CDAC 00000000 */   nop
/* 5D5B0 8006CDB0 6C01848E */  lw         $a0, 0x16C($s4)
/* 5D5B4 8006CDB4 06001216 */  bne        $s0, $s2, .L8006CDD0
/* 5D5B8 8006CDB8 FFDF0324 */   addiu     $v1, $zero, -0x2001
/* 5D5BC 8006CDBC 0000828C */  lw         $v0, 0x0($a0)
/* 5D5C0 8006CDC0 00000000 */  nop
/* 5D5C4 8006CDC4 24104300 */  and        $v0, $v0, $v1
/* 5D5C8 8006CDC8 86B40108 */  j          .L8006D218
/* 5D5CC 8006CDCC 000082AC */   sw        $v0, 0x0($a0)
.L8006CDD0:
/* 5D5D0 8006CDD0 0000828C */  lw         $v0, 0x0($a0)
/* 5D5D4 8006CDD4 00000000 */  nop
/* 5D5D8 8006CDD8 00204234 */  ori        $v0, $v0, 0x2000
/* 5D5DC 8006CDDC 86B40108 */  j          .L8006D218
/* 5D5E0 8006CDE0 000082AC */   sw        $v0, 0x0($a0)
.L8006CDE4:
/* 5D5E4 8006CDE4 0400628E */  lw         $v0, 0x4($s3)
/* 5D5E8 8006CDE8 00000000 */  nop
/* 5D5EC 8006CDEC 03004888 */  lwl        $t0, 0x3($v0)
/* 5D5F0 8006CDF0 00004898 */  lwr        $t0, 0x0($v0)
/* 5D5F4 8006CDF4 00000000 */  nop
/* 5D5F8 8006CDF8 070028AA */  swl        $t0, 0x7($s1)
/* 5D5FC 8006CDFC 040028BA */  swr        $t0, 0x4($s1)
/* 5D600 8006CE00 0400428C */  lw         $v0, 0x4($v0)
/* 5D604 8006CE04 FFF76334 */  ori        $v1, $v1, (0xFFEFF7FF & 0xFFFF)
/* 5D608 8006CE08 24104300 */  and        $v0, $v0, $v1
/* 5D60C 8006CE0C 0002033C */  lui        $v1, (0x2000000 >> 16)
/* 5D610 8006CE10 000022AE */  sw         $v0, 0x0($s1)
/* 5D614 8006CE14 24104300 */  and        $v0, $v0, $v1
/* 5D618 8006CE18 05004010 */  beqz       $v0, .L8006CE30
/* 5D61C 8006CE1C 21208002 */   addu      $a0, $s4, $zero
/* 5D620 8006CE20 1400828E */  lw         $v0, 0x14($s4)
/* 5D624 8006CE24 00000000 */  nop
/* 5D628 8006CE28 20004234 */  ori        $v0, $v0, 0x20
/* 5D62C 8006CE2C 140082AE */  sw         $v0, 0x14($s4)
.L8006CE30:
/* 5D630 8006CE30 B0A3010C */  jal        CheckPhysObAbility
/* 5D634 8006CE34 20000524 */   addiu     $a1, $zero, 0x20
/* 5D638 8006CE38 0C004010 */  beqz       $v0, .L8006CE6C
/* 5D63C 8006CE3C 21208002 */   addu      $a0, $s4, $zero
/* 5D640 8006CE40 A7B7010C */  jal        PhysObGetLight
/* 5D644 8006CE44 21208002 */   addu      $a0, $s4, $zero
/* 5D648 8006CE48 21284000 */  addu       $a1, $v0, $zero
/* 5D64C 8006CE4C 0000228E */  lw         $v0, 0x0($s1)
/* 5D650 8006CE50 0100033C */  lui        $v1, (0x10000 >> 16)
/* 5D654 8006CE54 24104300 */  and        $v0, $v0, $v1
/* 5D658 8006CE58 04004014 */  bnez       $v0, .L8006CE6C
/* 5D65C 8006CE5C 21208002 */   addu      $a0, $s4, $zero
/* 5D660 8006CE60 C3AB010C */  jal        PHYSOB_EndBurning
/* 5D664 8006CE64 21208002 */   addu      $a0, $s4, $zero
/* 5D668 8006CE68 21208002 */  addu       $a0, $s4, $zero
.L8006CE6C:
/* 5D66C 8006CE6C CFA3010C */  jal        CheckPhysObFamily
/* 5D670 8006CE70 02000524 */   addiu     $a1, $zero, 0x2
/* 5D674 8006CE74 13004010 */  beqz       $v0, .L8006CEC4
/* 5D678 8006CE78 21208002 */   addu      $a0, $s4, $zero
/* 5D67C 8006CE7C 6C01828E */  lw         $v0, 0x16C($s4)
/* 5D680 8006CE80 00000000 */  nop
/* 5D684 8006CE84 04004294 */  lhu        $v0, 0x4($v0)
/* 5D688 8006CE88 2400838E */  lw         $v1, 0x24($s4)
/* 5D68C 8006CE8C 01004230 */  andi       $v0, $v0, 0x1
/* 5D690 8006CE90 0C004010 */  beqz       $v0, .L8006CEC4
/* 5D694 8006CE94 21280000 */   addu      $a1, $zero, $zero
/* 5D698 8006CE98 0D006690 */  lbu        $a2, 0xD($v1)
/* 5D69C 8006CE9C 2138A000 */  addu       $a3, $a1, $zero
/* 5D6A0 8006CEA0 39C9010C */  jal        G2EmulationInstanceSetAnimation
/* 5D6A4 8006CEA4 1000A0AF */   sw        $zero, 0x10($sp)
/* 5D6A8 8006CEA8 21208002 */  addu       $a0, $s4, $zero
/* 5D6AC 8006CEAC 21280000 */  addu       $a1, $zero, $zero
/* 5D6B0 8006CEB0 71C9010C */  jal        G2EmulationInstanceSetMode
/* 5D6B4 8006CEB4 01000624 */   addiu     $a2, $zero, 0x1
/* 5D6B8 8006CEB8 67C7010C */  jal        G2EmulationInstancePlayAnimation
/* 5D6BC 8006CEBC 21208002 */   addu      $a0, $s4, $zero
/* 5D6C0 8006CEC0 21208002 */  addu       $a0, $s4, $zero
.L8006CEC4:
/* 5D6C4 8006CEC4 CFA3010C */  jal        CheckPhysObFamily
/* 5D6C8 8006CEC8 03000524 */   addiu     $a1, $zero, 0x3
/* 5D6CC 8006CECC D2004010 */  beqz       $v0, .L8006D218
/* 5D6D0 8006CED0 00000000 */   nop
/* 5D6D4 8006CED4 6C01828E */  lw         $v0, 0x16C($s4)
/* 5D6D8 8006CED8 00000000 */  nop
/* 5D6DC 8006CEDC 06004284 */  lh         $v0, 0x6($v0)
/* 5D6E0 8006CEE0 00000000 */  nop
/* 5D6E4 8006CEE4 CC004010 */  beqz       $v0, .L8006D218
/* 5D6E8 8006CEE8 21208002 */   addu      $a0, $s4, $zero
/* 5D6EC 8006CEEC 1000A0AF */  sw         $zero, 0x10($sp)
/* 5D6F0 8006CEF0 21280000 */  addu       $a1, $zero, $zero
/* 5D6F4 8006CEF4 2130A000 */  addu       $a2, $a1, $zero
/* 5D6F8 8006CEF8 39C9010C */  jal        G2EmulationInstanceSetAnimation
/* 5D6FC 8006CEFC 2138A000 */   addu      $a3, $a1, $zero
/* 5D700 8006CF00 21208002 */  addu       $a0, $s4, $zero
/* 5D704 8006CF04 21280000 */  addu       $a1, $zero, $zero
/* 5D708 8006CF08 71C9010C */  jal        G2EmulationInstanceSetMode
/* 5D70C 8006CF0C 01000624 */   addiu     $a2, $zero, 0x1
/* 5D710 8006CF10 67C7010C */  jal        G2EmulationInstancePlayAnimation
/* 5D714 8006CF14 21208002 */   addu      $a0, $s4, $zero
/* 5D718 8006CF18 86B40108 */  j          .L8006D218
/* 5D71C 8006CF1C 00000000 */   nop
.L8006CF20:
/* 5D720 8006CF20 BD002012 */  beqz       $s1, .L8006D218
/* 5D724 8006CF24 00000000 */   nop
/* 5D728 8006CF28 0E002296 */  lhu        $v0, 0xE($s1)
/* 5D72C 8006CF2C 00006396 */  lhu        $v1, 0x0($s3)
/* 5D730 8006CF30 00000000 */  nop
/* 5D734 8006CF34 21104300 */  addu       $v0, $v0, $v1
/* 5D738 8006CF38 0E0022A6 */  sh         $v0, 0xE($s1)
/* 5D73C 8006CF3C 10002296 */  lhu        $v0, 0x10($s1)
/* 5D740 8006CF40 02006396 */  lhu        $v1, 0x2($s3)
/* 5D744 8006CF44 00000000 */  nop
/* 5D748 8006CF48 21104300 */  addu       $v0, $v0, $v1
/* 5D74C 8006CF4C 100022A6 */  sh         $v0, 0x10($s1)
/* 5D750 8006CF50 12002296 */  lhu        $v0, 0x12($s1)
/* 5D754 8006CF54 04006396 */  lhu        $v1, 0x4($s3)
/* 5D758 8006CF58 00000000 */  nop
/* 5D75C 8006CF5C 21104300 */  addu       $v0, $v0, $v1
/* 5D760 8006CF60 86B40108 */  j          .L8006D218
/* 5D764 8006CF64 120022A6 */   sh        $v0, 0x12($s1)
.L8006CF68:
/* 5D768 8006CF68 2400908E */  lw         $s0, 0x24($s4)
/* 5D76C 8006CF6C 00000000 */  nop
/* 5D770 8006CF70 08000296 */  lhu        $v0, 0x8($s0)
/* 5D774 8006CF74 00000000 */  nop
/* 5D778 8006CF78 FFFF4224 */  addiu      $v0, $v0, -0x1
/* 5D77C 8006CF7C 00140200 */  sll        $v0, $v0, 16
/* 5D780 8006CF80 031C0200 */  sra        $v1, $v0, 16
/* 5D784 8006CF84 0700622C */  sltiu      $v0, $v1, 0x7
/* 5D788 8006CF88 A3004010 */  beqz       $v0, .L8006D218
/* 5D78C 8006CF8C 0180023C */   lui       $v0, %hi(jtbl_80011DA8)
/* 5D790 8006CF90 A81D4224 */  addiu      $v0, $v0, %lo(jtbl_80011DA8)
/* 5D794 8006CF94 80180300 */  sll        $v1, $v1, 2
/* 5D798 8006CF98 21186200 */  addu       $v1, $v1, $v0
/* 5D79C 8006CF9C 0000628C */  lw         $v0, 0x0($v1)
/* 5D7A0 8006CFA0 00000000 */  nop
/* 5D7A4 8006CFA4 08004000 */  jr         $v0
/* 5D7A8 8006CFA8 00000000 */   nop
.L8006CFAC:
/* 5D7AC 8006CFAC DEF0010C */  jal        HEALTHU_Pickup
/* 5D7B0 8006CFB0 21208002 */   addu      $a0, $s4, $zero
/* 5D7B4 8006CFB4 86B40108 */  j          .L8006D218
/* 5D7B8 8006CFB8 00000000 */   nop
.L8006CFBC:
/* 5D7BC 8006CFBC D7F0010C */  jal        MANNA_Pickup
/* 5D7C0 8006CFC0 00000000 */   nop
.L8006CFC4:
/* 5D7C4 8006CFC4 39D1000C */  jal        INSTANCE_PlainDeath
/* 5D7C8 8006CFC8 21208002 */   addu      $a0, $s4, $zero
/* 5D7CC 8006CFCC 86B40108 */  j          .L8006D218
/* 5D7D0 8006CFD0 00000000 */   nop
.L8006CFD4:
/* 5D7D4 8006CFD4 D7F0010C */  jal        MANNA_Pickup
/* 5D7D8 8006CFD8 00000000 */   nop
.L8006CFDC:
/* 5D7DC 8006CFDC 11000392 */  lbu        $v1, 0x11($s0)
/* 5D7E0 8006CFE0 FF000224 */  addiu      $v0, $zero, 0xFF
/* 5D7E4 8006CFE4 8C006210 */  beq        $v1, $v0, .L8006D218
/* 5D7E8 8006CFE8 21208002 */   addu      $a0, $s4, $zero
/* 5D7EC 8006CFEC A1C9010C */  jal        G2EmulationInstanceQueryAnimation
/* 5D7F0 8006CFF0 21280000 */   addu      $a1, $zero, $zero
/* 5D7F4 8006CFF4 11000392 */  lbu        $v1, 0x11($s0)
/* 5D7F8 8006CFF8 00000000 */  nop
/* 5D7FC 8006CFFC 86004310 */  beq        $v0, $v1, .L8006D218
/* 5D800 8006D000 0D80043C */   lui       $a0, %hi(D_800D1A10)
/* 5D804 8006D004 1C00828E */  lw         $v0, 0x1C($s4)
/* 5D808 8006D008 00000000 */  nop
/* 5D80C 8006D00C 2400458C */  lw         $a1, 0x24($v0)
/* 5D810 8006D010 06D1010C */  jal        printf
/* 5D814 8006D014 101A8424 */   addiu     $a0, $a0, %lo(D_800D1A10)
/* 5D818 8006D018 21208002 */  addu       $a0, $s4, $zero
/* 5D81C 8006D01C 21280000 */  addu       $a1, $zero, $zero
/* 5D820 8006D020 11000692 */  lbu        $a2, 0x11($s0)
/* 5D824 8006D024 2138A000 */  addu       $a3, $a1, $zero
/* 5D828 8006D028 39C9010C */  jal        G2EmulationInstanceSetAnimation
/* 5D82C 8006D02C 1000A0AF */   sw        $zero, 0x10($sp)
/* 5D830 8006D030 21208002 */  addu       $a0, $s4, $zero
/* 5D834 8006D034 21280000 */  addu       $a1, $zero, $zero
/* 5D838 8006D038 71C9010C */  jal        G2EmulationInstanceSetMode
/* 5D83C 8006D03C 01000624 */   addiu     $a2, $zero, 0x1
/* 5D840 8006D040 86B40108 */  j          .L8006D218
/* 5D844 8006D044 00000000 */   nop
.L8006D048:
/* 5D848 8006D048 04006012 */  beqz       $s3, .L8006D05C
/* 5D84C 8006D04C FFEF0324 */   addiu     $v1, $zero, -0x1001
/* 5D850 8006D050 0000228E */  lw         $v0, 0x0($s1)
/* 5D854 8006D054 31B40108 */  j          .L8006D0C4
/* 5D858 8006D058 24104300 */   and       $v0, $v0, $v1
.L8006D05C:
/* 5D85C 8006D05C 0000228E */  lw         $v0, 0x0($s1)
/* 5D860 8006D060 00000000 */  nop
/* 5D864 8006D064 00104234 */  ori        $v0, $v0, 0x1000
/* 5D868 8006D068 86B40108 */  j          .L8006D218
/* 5D86C 8006D06C 000022AE */   sw        $v0, 0x0($s1)
.L8006D070:
/* 5D870 8006D070 0000228E */  lw         $v0, 0x0($s1)
/* 5D874 8006D074 29B40108 */  j          .L8006D0A4
/* 5D878 8006D078 8000033C */   lui       $v1, (0x800000 >> 16)
.L8006D07C:
/* 5D87C 8006D07C C2B7010C */  jal        TurnOnCollisionPhysOb
/* 5D880 8006D080 21286002 */   addu      $a1, $s3, $zero
/* 5D884 8006D084 86B40108 */  j          .L8006D218
/* 5D888 8006D088 00000000 */   nop
.L8006D08C:
/* 5D88C 8006D08C 21208002 */  addu       $a0, $s4, $zero
/* 5D890 8006D090 EBB7010C */  jal        TurnOffCollisionPhysOb
/* 5D894 8006D094 21286002 */   addu      $a1, $s3, $zero
/* 5D898 8006D098 86B40108 */  j          .L8006D218
/* 5D89C 8006D09C 00000000 */   nop
.L8006D0A0:
/* 5D8A0 8006D0A0 0000228E */  lw         $v0, 0x0($s1)
.L8006D0A4:
/* 5D8A4 8006D0A4 00000000 */  nop
/* 5D8A8 8006D0A8 25104300 */  or         $v0, $v0, $v1
.L8006D0AC:
/* 5D8AC 8006D0AC 86B40108 */  j          .L8006D218
/* 5D8B0 8006D0B0 000022AE */   sw        $v0, 0x0($s1)
.L8006D0B4:
/* 5D8B4 8006D0B4 FFFE033C */  lui        $v1, (0xFEFFFFFF >> 16)
.L8006D0B8:
/* 5D8B8 8006D0B8 0000228E */  lw         $v0, 0x0($s1)
/* 5D8BC 8006D0BC FFFF6334 */  ori        $v1, $v1, (0xFEFFFFFF & 0xFFFF)
/* 5D8C0 8006D0C0 24104300 */  and        $v0, $v0, $v1
.L8006D0C4:
/* 5D8C4 8006D0C4 86B40108 */  j          .L8006D218
/* 5D8C8 8006D0C8 000022AE */   sw        $v0, 0x0($s1)
.L8006D0CC:
/* 5D8CC 8006D0CC A7B7010C */  jal        PhysObGetLight
/* 5D8D0 8006D0D0 21208002 */   addu      $a0, $s4, $zero
/* 5D8D4 8006D0D4 21284000 */  addu       $a1, $v0, $zero
/* 5D8D8 8006D0D8 4F00A010 */  beqz       $a1, .L8006D218
/* 5D8DC 8006D0DC 01000224 */   addiu     $v0, $zero, 0x1
/* 5D8E0 8006D0E0 0B006212 */  beq        $s3, $v0, .L8006D110
/* 5D8E4 8006D0E4 00000000 */   nop
/* 5D8E8 8006D0E8 05006012 */  beqz       $s3, .L8006D100
/* 5D8EC 8006D0EC 02000224 */   addiu     $v0, $zero, 0x2
/* 5D8F0 8006D0F0 0B006212 */  beq        $s3, $v0, .L8006D120
/* 5D8F4 8006D0F4 FFFF063C */   lui       $a2, (0xFFFF7FFF >> 16)
/* 5D8F8 8006D0F8 86B40108 */  j          .L8006D218
/* 5D8FC 8006D0FC 00000000 */   nop
.L8006D100:
/* 5D900 8006D100 BAAB010C */  jal        PHYSOB_StopBurning
/* 5D904 8006D104 21208002 */   addu      $a0, $s4, $zero
/* 5D908 8006D108 86B40108 */  j          .L8006D218
/* 5D90C 8006D10C 00000000 */   nop
.L8006D110:
/* 5D910 8006D110 A3AB010C */  jal        PHYSOB_StartBurning
/* 5D914 8006D114 21208002 */   addu      $a0, $s4, $zero
/* 5D918 8006D118 86B40108 */  j          .L8006D218
/* 5D91C 8006D11C 00000000 */   nop
.L8006D120:
/* 5D920 8006D120 6C01838E */  lw         $v1, 0x16C($s4)
/* 5D924 8006D124 FF7FC634 */  ori        $a2, $a2, (0xFFFF7FFF & 0xFFFF)
/* 5D928 8006D128 0000628C */  lw         $v0, 0x0($v1)
/* 5D92C 8006D12C 21208002 */  addu       $a0, $s4, $zero
/* 5D930 8006D130 340060A4 */  sh         $zero, 0x34($v1)
/* 5D934 8006D134 24104600 */  and        $v0, $v0, $a2
/* 5D938 8006D138 C3AB010C */  jal        PHYSOB_EndBurning
/* 5D93C 8006D13C 000062AC */   sw        $v0, 0x0($v1)
/* 5D940 8006D140 86B40108 */  j          .L8006D218
/* 5D944 8006D144 00000000 */   nop
.L8006D148:
/* 5D948 8006D148 21208002 */  addu       $a0, $s4, $zero
/* 5D94C 8006D14C F7F6000C */  jal        ScriptKillInstance
/* 5D950 8006D150 05000524 */   addiu     $a1, $zero, 0x5
/* 5D954 8006D154 86B40108 */  j          .L8006D218
/* 5D958 8006D158 00000000 */   nop
.L8006D15C:
/* 5D95C 8006D15C 21208002 */  addu       $a0, $s4, $zero
/* 5D960 8006D160 F7F6000C */  jal        ScriptKillInstance
/* 5D964 8006D164 21286002 */   addu      $a1, $s3, $zero
/* 5D968 8006D168 86B40108 */  j          .L8006D218
/* 5D96C 8006D16C 00000000 */   nop
.L8006D170:
/* 5D970 8006D170 21208002 */  addu       $a0, $s4, $zero
/* 5D974 8006D174 CFA3010C */  jal        CheckPhysObFamily
/* 5D978 8006D178 02000524 */   addiu     $a1, $zero, 0x2
/* 5D97C 8006D17C 26004010 */  beqz       $v0, .L8006D218
/* 5D980 8006D180 00000000 */   nop
/* 5D984 8006D184 6C01828E */  lw         $v0, 0x16C($s4)
/* 5D988 8006D188 86B40108 */  j          .L8006D218
/* 5D98C 8006D18C 040053A4 */   sh        $s3, 0x4($v0)
.L8006D190:
/* 5D990 8006D190 0C00628E */  lw         $v0, 0xC($s3)
/* 5D994 8006D194 00000000 */  nop
/* 5D998 8006D198 1000A2AF */  sw         $v0, 0x10($sp)
/* 5D99C 8006D19C 0400668E */  lw         $a2, 0x4($s3)
/* 5D9A0 8006D1A0 0800678E */  lw         $a3, 0x8($s3)
/* 5D9A4 8006D1A4 39C9010C */  jal        G2EmulationInstanceSetAnimation
/* 5D9A8 8006D1A8 21280000 */   addu      $a1, $zero, $zero
/* 5D9AC 8006D1AC 21208002 */  addu       $a0, $s4, $zero
/* 5D9B0 8006D1B0 1000668E */  lw         $a2, 0x10($s3)
/* 5D9B4 8006D1B4 71C9010C */  jal        G2EmulationInstanceSetMode
/* 5D9B8 8006D1B8 21280000 */   addu      $a1, $zero, $zero
/* 5D9BC 8006D1BC 86B40108 */  j          .L8006D218
/* 5D9C0 8006D1C0 00000000 */   nop
.L8006D1C4:
/* 5D9C4 8006D1C4 14006012 */  beqz       $s3, .L8006D218
/* 5D9C8 8006D1C8 00000000 */   nop
/* 5D9CC 8006D1CC 2400828E */  lw         $v0, 0x24($s4)
/* 5D9D0 8006D1D0 00000000 */  nop
/* 5D9D4 8006D1D4 02004394 */  lhu        $v1, 0x2($v0)
/* 5D9D8 8006D1D8 07000224 */  addiu      $v0, $zero, 0x7
/* 5D9DC 8006D1DC 0E006214 */  bne        $v1, $v0, .L8006D218
/* 5D9E0 8006D1E0 00000000 */   nop
/* 5D9E4 8006D1E4 2C00848E */  lw         $a0, 0x2C($s4)
/* 5D9E8 8006D1E8 00000000 */  nop
/* 5D9EC 8006D1EC 0A008010 */  beqz       $a0, .L8006D218
/* 5D9F0 8006D1F0 00000000 */   nop
/* 5D9F4 8006D1F4 92D1000C */  jal        INSTANCE_Query
/* 5D9F8 8006D1F8 01000524 */   addiu     $a1, $zero, 0x1
/* 5D9FC 8006D1FC 0A004230 */  andi       $v0, $v0, 0xA
/* 5DA00 8006D200 05004010 */  beqz       $v0, .L8006D218
/* 5DA04 8006D204 00000000 */   nop
/* 5DA08 8006D208 1400828E */  lw         $v0, 0x14($s4)
/* 5DA0C 8006D20C 00000000 */  nop
/* 5DA10 8006D210 20004234 */  ori        $v0, $v0, 0x20
/* 5DA14 8006D214 140082AE */  sw         $v0, 0x14($s4)
.L8006D218:
/* 5DA18 8006D218 2C00BF8F */  lw         $ra, 0x2C($sp)
/* 5DA1C 8006D21C 2800B48F */  lw         $s4, 0x28($sp)
/* 5DA20 8006D220 2400B38F */  lw         $s3, 0x24($sp)
/* 5DA24 8006D224 2000B28F */  lw         $s2, 0x20($sp)
/* 5DA28 8006D228 1C00B18F */  lw         $s1, 0x1C($sp)
/* 5DA2C 8006D22C 1800B08F */  lw         $s0, 0x18($sp)
/* 5DA30 8006D230 0800E003 */  jr         $ra
/* 5DA34 8006D234 3000BD27 */   addiu     $sp, $sp, 0x30
.size PhysicalObjectPost, . - PhysicalObjectPost
