.set noat      /* allow manual use of $at */
.set noreorder /* don't insert nops after branches */

.section .rodata
.align 3
dlabel jtbl_80010C68
/* 1468 80010C68 183F0680 */ .word .L80063F18
/* 146C 80010C6C 243F0680 */ .word .L80063F24
/* 1470 80010C70 303F0680 */ .word .L80063F30
/* 1474 80010C74 C83F0680 */ .word .L80063FC8
/* 1478 80010C78 C83F0680 */ .word .L80063FC8
/* 147C 80010C7C C83F0680 */ .word .L80063FC8
/* 1480 80010C80 C83F0680 */ .word .L80063FC8
/* 1484 80010C84 C83F0680 */ .word .L80063FC8
/* 1488 80010C88 C83F0680 */ .word .L80063FC8
/* 148C 80010C8C C83F0680 */ .word .L80063FC8
/* 1490 80010C90 C83F0680 */ .word .L80063FC8
/* 1494 80010C94 C83F0680 */ .word .L80063FC8
/* 1498 80010C98 C83F0680 */ .word .L80063FC8
/* 149C 80010C9C C83F0680 */ .word .L80063FC8
/* 14A0 80010CA0 C83F0680 */ .word .L80063FC8
/* 14A4 80010CA4 C83F0680 */ .word .L80063FC8
/* 14A8 80010CA8 C83F0680 */ .word .L80063FC8
/* 14AC 80010CAC 443F0680 */ .word .L80063F44
/* 14B0 80010CB0 683F0680 */ .word .L80063F68
/* 14B4 80010CB4 943F0680 */ .word .L80063F94
.size jtbl_80010C68, . - jtbl_80010C68


.section .text
/* Generated by spimdisasm 1.21.0 */

glabel EVENT_TransformVector3dAttribute
/* 546E0 80063EE0 E8FFBD27 */  addiu      $sp, $sp, -0x18
/* 546E4 80063EE4 1000BFAF */  sw         $ra, 0x10($sp)
/* 546E8 80063EE8 FAFFC324 */  addiu      $v1, $a2, -0x6
/* 546EC 80063EEC 1400622C */  sltiu      $v0, $v1, 0x14
/* 546F0 80063EF0 35004010 */  beqz       $v0, .L80063FC8
/* 546F4 80063EF4 2120A000 */   addu      $a0, $a1, $zero
/* 546F8 80063EF8 0180023C */  lui        $v0, %hi(jtbl_80010C68)
/* 546FC 80063EFC 680C4224 */  addiu      $v0, $v0, %lo(jtbl_80010C68)
/* 54700 80063F00 80180300 */  sll        $v1, $v1, 2
/* 54704 80063F04 21186200 */  addu       $v1, $v1, $v0
/* 54708 80063F08 0000628C */  lw         $v0, 0x0($v1)
/* 5470C 80063F0C 00000000 */  nop
/* 54710 80063F10 08004000 */  jr         $v0
/* 54714 80063F14 00000000 */   nop
.L80063F18:
/* 54718 80063F18 04008584 */  lh         $a1, 0x4($a0)
/* 5471C 80063F1C CD8F0108 */  j          .L80063F34
/* 54720 80063F20 00000000 */   nop
.L80063F24:
/* 54724 80063F24 06008584 */  lh         $a1, 0x6($a0)
/* 54728 80063F28 CD8F0108 */  j          .L80063F34
/* 5472C 80063F2C 00000000 */   nop
.L80063F30:
/* 54730 80063F30 08008584 */  lh         $a1, 0x8($a0)
.L80063F34:
/* 54734 80063F34 9588010C */  jal        EVENT_ChangeOperandToNumber
/* 54738 80063F38 21300000 */   addu      $a2, $zero, $zero
/* 5473C 80063F3C F38F0108 */  j          .L80063FCC
/* 54740 80063F40 01000624 */   addiu     $a2, $zero, 0x1
.L80063F44:
/* 54744 80063F44 01000624 */  addiu      $a2, $zero, 0x1
/* 54748 80063F48 0200E394 */  lhu        $v1, 0x2($a3)
/* 5474C 80063F4C FFFF0224 */  addiu      $v0, $zero, -0x1
/* 54750 80063F50 0E0082A4 */  sh         $v0, 0xE($a0)
/* 54754 80063F54 100082A4 */  sh         $v0, 0x10($a0)
/* 54758 80063F58 2110C000 */  addu       $v0, $a2, $zero
/* 5475C 80063F5C 5CA482AF */  sw         $v0, %gp_rel(MoveCodeStreamExtra)($gp)
/* 54760 80063F60 F38F0108 */  j          .L80063FCC
/* 54764 80063F64 0C0083A4 */   sh        $v1, 0xC($a0)
.L80063F68:
/* 54768 80063F68 0200E724 */  addiu      $a3, $a3, 0x2
/* 5476C 80063F6C 02000224 */  addiu      $v0, $zero, 0x2
/* 54770 80063F70 5CA482AF */  sw         $v0, %gp_rel(MoveCodeStreamExtra)($gp)
/* 54774 80063F74 0000E294 */  lhu        $v0, 0x0($a3)
/* 54778 80063F78 01000624 */  addiu      $a2, $zero, 0x1
/* 5477C 80063F7C 0C0082A4 */  sh         $v0, 0xC($a0)
/* 54780 80063F80 0200E394 */  lhu        $v1, 0x2($a3)
/* 54784 80063F84 FFFF0224 */  addiu      $v0, $zero, -0x1
/* 54788 80063F88 100082A4 */  sh         $v0, 0x10($a0)
/* 5478C 80063F8C F38F0108 */  j          .L80063FCC
/* 54790 80063F90 0E0083A4 */   sh        $v1, 0xE($a0)
.L80063F94:
/* 54794 80063F94 0200E724 */  addiu      $a3, $a3, 0x2
/* 54798 80063F98 03000224 */  addiu      $v0, $zero, 0x3
/* 5479C 80063F9C 5CA482AF */  sw         $v0, %gp_rel(MoveCodeStreamExtra)($gp)
/* 547A0 80063FA0 0000E294 */  lhu        $v0, 0x0($a3)
/* 547A4 80063FA4 0200E724 */  addiu      $a3, $a3, 0x2
/* 547A8 80063FA8 0C0082A4 */  sh         $v0, 0xC($a0)
/* 547AC 80063FAC 0000E294 */  lhu        $v0, 0x0($a3)
/* 547B0 80063FB0 00000000 */  nop
/* 547B4 80063FB4 0E0082A4 */  sh         $v0, 0xE($a0)
/* 547B8 80063FB8 0200E294 */  lhu        $v0, 0x2($a3)
/* 547BC 80063FBC 01000624 */  addiu      $a2, $zero, 0x1
/* 547C0 80063FC0 F38F0108 */  j          .L80063FCC
/* 547C4 80063FC4 100082A4 */   sh        $v0, 0x10($a0)
.L80063FC8:
/* 547C8 80063FC8 21300000 */  addu       $a2, $zero, $zero
.L80063FCC:
/* 547CC 80063FCC 1000BF8F */  lw         $ra, 0x10($sp)
/* 547D0 80063FD0 2110C000 */  addu       $v0, $a2, $zero
/* 547D4 80063FD4 0800E003 */  jr         $ra
/* 547D8 80063FD8 1800BD27 */   addiu     $sp, $sp, 0x18
.size EVENT_TransformVector3dAttribute, . - EVENT_TransformVector3dAttribute
